/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.projects;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.newscatcher.catchall.core.CatchAllApiApiException;
import com.newscatcher.catchall.core.CatchAllApiException;
import com.newscatcher.catchall.core.CatchAllApiHttpResponse;
import com.newscatcher.catchall.core.ClientOptions;
import com.newscatcher.catchall.core.MediaTypes;
import com.newscatcher.catchall.core.ObjectMappers;
import com.newscatcher.catchall.core.QueryStringMapper;
import com.newscatcher.catchall.core.RequestOptions;
import com.newscatcher.catchall.core.RetryInterceptor;
import com.newscatcher.catchall.errors.BadRequestError;
import com.newscatcher.catchall.errors.ForbiddenError;
import com.newscatcher.catchall.errors.NotFoundError;
import com.newscatcher.catchall.errors.UnprocessableEntityError;
import com.newscatcher.catchall.resources.projects.requests.AddResourceRequestDto;
import com.newscatcher.catchall.resources.projects.requests.CreateProjectRequestDto;
import com.newscatcher.catchall.resources.projects.requests.DeleteProjectRequest;
import com.newscatcher.catchall.resources.projects.requests.GetProjectOverviewRequest;
import com.newscatcher.catchall.resources.projects.requests.GetProjectRequest;
import com.newscatcher.catchall.resources.projects.requests.ListProjectResourcesRequest;
import com.newscatcher.catchall.resources.projects.requests.ListProjectsRequest;
import com.newscatcher.catchall.resources.projects.requests.RemoveResourceFromProjectRequest;
import com.newscatcher.catchall.resources.projects.requests.UpdateProjectRequestDto;
import com.newscatcher.catchall.types.AddResourceResponseDto;
import com.newscatcher.catchall.types.CreateProjectResponseDto;
import com.newscatcher.catchall.types.Error;
import com.newscatcher.catchall.types.ProjectListResponseDto;
import com.newscatcher.catchall.types.ProjectOverviewResponseDto;
import com.newscatcher.catchall.types.ProjectResourceListResponseDto;
import com.newscatcher.catchall.types.ProjectResourceType;
import com.newscatcher.catchall.types.ProjectResponseDto;
import com.newscatcher.catchall.types.RemoveResourceResponseDto;
import com.newscatcher.catchall.types.UpdateProjectResponseDto;
import com.newscatcher.catchall.types.ValidationErrorResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawProjectsClient {
    protected final ClientOptions clientOptions;

    public RawProjectsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns all projects visible to the authenticated user.
     */
    public CatchAllApiHttpResponse<ProjectListResponseDto> listProjects() {
        return listProjects(ListProjectsRequest.builder().build());
    }

    /**
     * Returns all projects visible to the authenticated user.
     */
    public CatchAllApiHttpResponse<ProjectListResponseDto> listProjects(RequestOptions requestOptions) {
        return listProjects(ListProjectsRequest.builder().build(), requestOptions);
    }

    /**
     * Returns all projects visible to the authenticated user.
     */
    public CatchAllApiHttpResponse<ProjectListResponseDto> listProjects(ListProjectsRequest request) {
        return listProjects(request, null);
    }

    /**
     * Returns all projects visible to the authenticated user.
     */
    public CatchAllApiHttpResponse<ProjectListResponseDto> listProjects(
            ListProjectsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/projects");
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPageSize().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page_size", request.getPageSize().get(), false);
        }
        if (request.getSearch().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "search", request.getSearch().get(), false);
        }
        if (request.getOwnership().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "ownership", request.getOwnership().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ProjectListResponseDto.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ValidationErrorResponse.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Creates a new project.
     */
    public CatchAllApiHttpResponse<CreateProjectResponseDto> createProject(CreateProjectRequestDto request) {
        return createProject(request, null);
    }

    /**
     * Creates a new project.
     */
    public CatchAllApiHttpResponse<CreateProjectResponseDto> createProject(
            CreateProjectRequestDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/projects");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateProjectResponseDto.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ValidationErrorResponse.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns a single project by ID.
     */
    public CatchAllApiHttpResponse<ProjectResponseDto> getProject(String projectId) {
        return getProject(projectId, GetProjectRequest.builder().build());
    }

    /**
     * Returns a single project by ID.
     */
    public CatchAllApiHttpResponse<ProjectResponseDto> getProject(String projectId, RequestOptions requestOptions) {
        return getProject(projectId, GetProjectRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a single project by ID.
     */
    public CatchAllApiHttpResponse<ProjectResponseDto> getProject(String projectId, GetProjectRequest request) {
        return getProject(projectId, request, null);
    }

    /**
     * Returns a single project by ID.
     */
    public CatchAllApiHttpResponse<ProjectResponseDto> getProject(
            String projectId, GetProjectRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/projects")
                .addPathSegment(projectId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ProjectResponseDto.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Deletes a project. By default, assigned resources are unassigned but not deleted.
     */
    public CatchAllApiHttpResponse<Void> deleteProject(String projectId) {
        return deleteProject(projectId, DeleteProjectRequest.builder().build());
    }

    /**
     * Deletes a project. By default, assigned resources are unassigned but not deleted.
     */
    public CatchAllApiHttpResponse<Void> deleteProject(String projectId, RequestOptions requestOptions) {
        return deleteProject(projectId, DeleteProjectRequest.builder().build(), requestOptions);
    }

    /**
     * Deletes a project. By default, assigned resources are unassigned but not deleted.
     */
    public CatchAllApiHttpResponse<Void> deleteProject(String projectId, DeleteProjectRequest request) {
        return deleteProject(projectId, request, null);
    }

    /**
     * Deletes a project. By default, assigned resources are unassigned but not deleted.
     */
    public CatchAllApiHttpResponse<Void> deleteProject(
            String projectId, DeleteProjectRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/projects")
                .addPathSegment(projectId);
        if (request.getDeleteResources().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "delete_resources", request.getDeleteResources().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Updates the name or description of an existing project.
     */
    public CatchAllApiHttpResponse<UpdateProjectResponseDto> updateProject(String projectId) {
        return updateProject(projectId, UpdateProjectRequestDto.builder().build());
    }

    /**
     * Updates the name or description of an existing project.
     */
    public CatchAllApiHttpResponse<UpdateProjectResponseDto> updateProject(
            String projectId, RequestOptions requestOptions) {
        return updateProject(projectId, UpdateProjectRequestDto.builder().build(), requestOptions);
    }

    /**
     * Updates the name or description of an existing project.
     */
    public CatchAllApiHttpResponse<UpdateProjectResponseDto> updateProject(
            String projectId, UpdateProjectRequestDto request) {
        return updateProject(projectId, request, null);
    }

    /**
     * Updates the name or description of an existing project.
     */
    public CatchAllApiHttpResponse<UpdateProjectResponseDto> updateProject(
            String projectId, UpdateProjectRequestDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/projects")
                .addPathSegment(projectId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateProjectResponseDto.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ValidationErrorResponse.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns resource counts for a project, grouped by type and status.
     * <p>For <code>jobs</code> and <code>monitors</code>, counts are broken down by status (for example, <code>completed</code>, <code>failed</code>). For <code>datasets</code> and <code>monitor_groups</code>, only a <code>total</code> count is returned.</p>
     */
    public CatchAllApiHttpResponse<ProjectOverviewResponseDto> getProjectOverview(String projectId) {
        return getProjectOverview(projectId, GetProjectOverviewRequest.builder().build());
    }

    /**
     * Returns resource counts for a project, grouped by type and status.
     * <p>For <code>jobs</code> and <code>monitors</code>, counts are broken down by status (for example, <code>completed</code>, <code>failed</code>). For <code>datasets</code> and <code>monitor_groups</code>, only a <code>total</code> count is returned.</p>
     */
    public CatchAllApiHttpResponse<ProjectOverviewResponseDto> getProjectOverview(
            String projectId, RequestOptions requestOptions) {
        return getProjectOverview(projectId, GetProjectOverviewRequest.builder().build(), requestOptions);
    }

    /**
     * Returns resource counts for a project, grouped by type and status.
     * <p>For <code>jobs</code> and <code>monitors</code>, counts are broken down by status (for example, <code>completed</code>, <code>failed</code>). For <code>datasets</code> and <code>monitor_groups</code>, only a <code>total</code> count is returned.</p>
     */
    public CatchAllApiHttpResponse<ProjectOverviewResponseDto> getProjectOverview(
            String projectId, GetProjectOverviewRequest request) {
        return getProjectOverview(projectId, request, null);
    }

    /**
     * Returns resource counts for a project, grouped by type and status.
     * <p>For <code>jobs</code> and <code>monitors</code>, counts are broken down by status (for example, <code>completed</code>, <code>failed</code>). For <code>datasets</code> and <code>monitor_groups</code>, only a <code>total</code> count is returned.</p>
     */
    public CatchAllApiHttpResponse<ProjectOverviewResponseDto> getProjectOverview(
            String projectId, GetProjectOverviewRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/projects")
                .addPathSegment(projectId)
                .addPathSegments("overview");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ProjectOverviewResponseDto.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns all resources assigned to a project, with optional filtering by type.
     */
    public CatchAllApiHttpResponse<ProjectResourceListResponseDto> listProjectResources(String projectId) {
        return listProjectResources(
                projectId, ListProjectResourcesRequest.builder().build());
    }

    /**
     * Returns all resources assigned to a project, with optional filtering by type.
     */
    public CatchAllApiHttpResponse<ProjectResourceListResponseDto> listProjectResources(
            String projectId, RequestOptions requestOptions) {
        return listProjectResources(
                projectId, ListProjectResourcesRequest.builder().build(), requestOptions);
    }

    /**
     * Returns all resources assigned to a project, with optional filtering by type.
     */
    public CatchAllApiHttpResponse<ProjectResourceListResponseDto> listProjectResources(
            String projectId, ListProjectResourcesRequest request) {
        return listProjectResources(projectId, request, null);
    }

    /**
     * Returns all resources assigned to a project, with optional filtering by type.
     */
    public CatchAllApiHttpResponse<ProjectResourceListResponseDto> listProjectResources(
            String projectId, ListProjectResourcesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/projects")
                .addPathSegment(projectId)
                .addPathSegments("resources");
        if (request.getResourceType().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "resource_type", request.getResourceType().get(), false);
        }
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPageSize().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page_size", request.getPageSize().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ProjectResourceListResponseDto.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ValidationErrorResponse.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Assigns one or more existing resources to a project in a single request.
     */
    public CatchAllApiHttpResponse<AddResourceResponseDto> addResourceToProject(
            String projectId, AddResourceRequestDto request) {
        return addResourceToProject(projectId, request, null);
    }

    /**
     * Assigns one or more existing resources to a project in a single request.
     */
    public CatchAllApiHttpResponse<AddResourceResponseDto> addResourceToProject(
            String projectId, AddResourceRequestDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/projects")
                .addPathSegment(projectId)
                .addPathSegments("resources");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AddResourceResponseDto.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Removes a resource from a project. The resource itself is not
     * deleted — it becomes unassigned and continues to exist.
     */
    public CatchAllApiHttpResponse<RemoveResourceResponseDto> removeResourceFromProject(
            String projectId, ProjectResourceType resourceType, String resourceId) {
        return removeResourceFromProject(
                projectId,
                resourceType,
                resourceId,
                RemoveResourceFromProjectRequest.builder().build());
    }

    /**
     * Removes a resource from a project. The resource itself is not
     * deleted — it becomes unassigned and continues to exist.
     */
    public CatchAllApiHttpResponse<RemoveResourceResponseDto> removeResourceFromProject(
            String projectId, ProjectResourceType resourceType, String resourceId, RequestOptions requestOptions) {
        return removeResourceFromProject(
                projectId,
                resourceType,
                resourceId,
                RemoveResourceFromProjectRequest.builder().build(),
                requestOptions);
    }

    /**
     * Removes a resource from a project. The resource itself is not
     * deleted — it becomes unassigned and continues to exist.
     */
    public CatchAllApiHttpResponse<RemoveResourceResponseDto> removeResourceFromProject(
            String projectId,
            ProjectResourceType resourceType,
            String resourceId,
            RemoveResourceFromProjectRequest request) {
        return removeResourceFromProject(projectId, resourceType, resourceId, request, null);
    }

    /**
     * Removes a resource from a project. The resource itself is not
     * deleted — it becomes unassigned and continues to exist.
     */
    public CatchAllApiHttpResponse<RemoveResourceResponseDto> removeResourceFromProject(
            String projectId,
            ProjectResourceType resourceType,
            String resourceId,
            RemoveResourceFromProjectRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/projects")
                .addPathSegment(projectId)
                .addPathSegments("resources")
                .addPathSegment(resourceType.toString())
                .addPathSegment(resourceId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RemoveResourceResponseDto.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }
}
