/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AdditionalAttributes.Builder.class)
public final class AdditionalAttributes {
    private final Optional<CompanyAttributes> companyAttributes;

    private final Map<String, Object> additionalProperties;

    private AdditionalAttributes(
            Optional<CompanyAttributes> companyAttributes, Map<String, Object> additionalProperties) {
        this.companyAttributes = companyAttributes;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("company_attributes")
    public Optional<CompanyAttributes> getCompanyAttributes() {
        return companyAttributes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AdditionalAttributes && equalTo((AdditionalAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AdditionalAttributes other) {
        return companyAttributes.equals(other.companyAttributes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.companyAttributes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<CompanyAttributes> companyAttributes = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AdditionalAttributes other) {
            companyAttributes(other.getCompanyAttributes());
            return this;
        }

        @JsonSetter(value = "company_attributes", nulls = Nulls.SKIP)
        public Builder companyAttributes(Optional<CompanyAttributes> companyAttributes) {
            this.companyAttributes = companyAttributes;
            return this;
        }

        public Builder companyAttributes(CompanyAttributes companyAttributes) {
            this.companyAttributes = Optional.ofNullable(companyAttributes);
            return this;
        }

        public AdditionalAttributes build() {
            return new AdditionalAttributes(companyAttributes, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
