/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ApiKeyAuthDto.Builder.class)
public final class ApiKeyAuthDto {
    private final String header;

    private final String value;

    private final Map<String, Object> additionalProperties;

    private ApiKeyAuthDto(String header, String value, Map<String, Object> additionalProperties) {
        this.header = header;
        this.value = value;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return HTTP header name for the API key.
     */
    @JsonProperty("header")
    public String getHeader() {
        return header;
    }

    /**
     * @return API key value.
     */
    @JsonProperty("value")
    public String getValue() {
        return value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ApiKeyAuthDto && equalTo((ApiKeyAuthDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ApiKeyAuthDto other) {
        return header.equals(other.header) && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.header, this.value);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static HeaderStage builder() {
        return new Builder();
    }

    public interface HeaderStage {
        /**
         * <p>HTTP header name for the API key.</p>
         */
        ValueStage header(@NotNull String header);

        Builder from(ApiKeyAuthDto other);
    }

    public interface ValueStage {
        /**
         * <p>API key value.</p>
         */
        _FinalStage value(@NotNull String value);
    }

    public interface _FinalStage {
        ApiKeyAuthDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements HeaderStage, ValueStage, _FinalStage {
        private String header;

        private String value;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ApiKeyAuthDto other) {
            header(other.getHeader());
            value(other.getValue());
            return this;
        }

        /**
         * <p>HTTP header name for the API key.</p>
         * <p>HTTP header name for the API key.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("header")
        public ValueStage header(@NotNull String header) {
            this.header = Objects.requireNonNull(header, "header must not be null");
            return this;
        }

        /**
         * <p>API key value.</p>
         * <p>API key value.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("value")
        public _FinalStage value(@NotNull String value) {
            this.value = Objects.requireNonNull(value, "value must not be null");
            return this;
        }

        @java.lang.Override
        public ApiKeyAuthDto build() {
            return new ApiKeyAuthDto(header, value, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
