/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BaseRecord.Builder.class)
public final class BaseRecord implements IBaseRecord {
    private final String recordId;

    private final String recordTitle;

    private final BaseRecordEnrichment enrichment;

    private final Map<String, Object> additionalProperties;

    private BaseRecord(
            String recordId,
            String recordTitle,
            BaseRecordEnrichment enrichment,
            Map<String, Object> additionalProperties) {
        this.recordId = recordId;
        this.recordTitle = recordTitle;
        this.enrichment = enrichment;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier for the record.
     */
    @JsonProperty("record_id")
    @java.lang.Override
    public String getRecordId() {
        return recordId;
    }

    /**
     * @return Short title summarizing the record.
     */
    @JsonProperty("record_title")
    @java.lang.Override
    public String getRecordTitle() {
        return recordTitle;
    }

    /**
     * @return Structured data extracted from web pages. Schema is dynamically generated per job. Field names are chosen semantically to match the content.
     * <p><strong>Note:</strong> The system always includes the <code>enrichment_confidence</code> field within the <code>enrichment</code> object, regardless of whether enrichments are generated or specified by you.</p>
     * <p>For integration guidance, see <a href="https://www.newscatcherapi.com/docs/web-search-api/guides-and-concepts/dynamic-schemas">Dynamic schemas</a></p>
     */
    @JsonProperty("enrichment")
    public BaseRecordEnrichment getEnrichment() {
        return enrichment;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BaseRecord && equalTo((BaseRecord) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BaseRecord other) {
        return recordId.equals(other.recordId)
                && recordTitle.equals(other.recordTitle)
                && enrichment.equals(other.enrichment);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.recordId, this.recordTitle, this.enrichment);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RecordIdStage builder() {
        return new Builder();
    }

    public interface RecordIdStage {
        /**
         * <p>Unique identifier for the record.</p>
         */
        RecordTitleStage recordId(@NotNull String recordId);

        Builder from(BaseRecord other);
    }

    public interface RecordTitleStage {
        /**
         * <p>Short title summarizing the record.</p>
         */
        EnrichmentStage recordTitle(@NotNull String recordTitle);
    }

    public interface EnrichmentStage {
        /**
         * <p>Structured data extracted from web pages. Schema is dynamically generated per job. Field names are chosen semantically to match the content.</p>
         * <p><strong>Note:</strong> The system always includes the <code>enrichment_confidence</code> field within the <code>enrichment</code> object, regardless of whether enrichments are generated or specified by you.</p>
         * <p>For integration guidance, see <a href="https://www.newscatcherapi.com/docs/web-search-api/guides-and-concepts/dynamic-schemas">Dynamic schemas</a></p>
         */
        _FinalStage enrichment(@NotNull BaseRecordEnrichment enrichment);
    }

    public interface _FinalStage {
        BaseRecord build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements RecordIdStage, RecordTitleStage, EnrichmentStage, _FinalStage {
        private String recordId;

        private String recordTitle;

        private BaseRecordEnrichment enrichment;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BaseRecord other) {
            recordId(other.getRecordId());
            recordTitle(other.getRecordTitle());
            enrichment(other.getEnrichment());
            return this;
        }

        /**
         * <p>Unique identifier for the record.</p>
         * <p>Unique identifier for the record.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("record_id")
        public RecordTitleStage recordId(@NotNull String recordId) {
            this.recordId = Objects.requireNonNull(recordId, "recordId must not be null");
            return this;
        }

        /**
         * <p>Short title summarizing the record.</p>
         * <p>Short title summarizing the record.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("record_title")
        public EnrichmentStage recordTitle(@NotNull String recordTitle) {
            this.recordTitle = Objects.requireNonNull(recordTitle, "recordTitle must not be null");
            return this;
        }

        /**
         * <p>Structured data extracted from web pages. Schema is dynamically generated per job. Field names are chosen semantically to match the content.</p>
         * <p><strong>Note:</strong> The system always includes the <code>enrichment_confidence</code> field within the <code>enrichment</code> object, regardless of whether enrichments are generated or specified by you.</p>
         * <p>For integration guidance, see <a href="https://www.newscatcherapi.com/docs/web-search-api/guides-and-concepts/dynamic-schemas">Dynamic schemas</a></p>
         * <p>Structured data extracted from web pages. Schema is dynamically generated per job. Field names are chosen semantically to match the content.</p>
         * <p><strong>Note:</strong> The system always includes the <code>enrichment_confidence</code> field within the <code>enrichment</code> object, regardless of whether enrichments are generated or specified by you.</p>
         * <p>For integration guidance, see <a href="https://www.newscatcherapi.com/docs/web-search-api/guides-and-concepts/dynamic-schemas">Dynamic schemas</a></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("enrichment")
        public _FinalStage enrichment(@NotNull BaseRecordEnrichment enrichment) {
            this.enrichment = Objects.requireNonNull(enrichment, "enrichment must not be null");
            return this;
        }

        @java.lang.Override
        public BaseRecord build() {
            return new BaseRecord(recordId, recordTitle, enrichment, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
