/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BasicAuthDto.Builder.class)
public final class BasicAuthDto {
    private final String username;

    private final String password;

    private final Map<String, Object> additionalProperties;

    private BasicAuthDto(String username, String password, Map<String, Object> additionalProperties) {
        this.username = username;
        this.password = password;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Basic auth username.
     */
    @JsonProperty("username")
    public String getUsername() {
        return username;
    }

    /**
     * @return Basic auth password.
     */
    @JsonProperty("password")
    public String getPassword() {
        return password;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BasicAuthDto && equalTo((BasicAuthDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BasicAuthDto other) {
        return username.equals(other.username) && password.equals(other.password);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.username, this.password);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static UsernameStage builder() {
        return new Builder();
    }

    public interface UsernameStage {
        /**
         * <p>Basic auth username.</p>
         */
        PasswordStage username(@NotNull String username);

        Builder from(BasicAuthDto other);
    }

    public interface PasswordStage {
        /**
         * <p>Basic auth password.</p>
         */
        _FinalStage password(@NotNull String password);
    }

    public interface _FinalStage {
        BasicAuthDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements UsernameStage, PasswordStage, _FinalStage {
        private String username;

        private String password;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BasicAuthDto other) {
            username(other.getUsername());
            password(other.getPassword());
            return this;
        }

        /**
         * <p>Basic auth username.</p>
         * <p>Basic auth username.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("username")
        public PasswordStage username(@NotNull String username) {
            this.username = Objects.requireNonNull(username, "username must not be null");
            return this;
        }

        /**
         * <p>Basic auth password.</p>
         * <p>Basic auth password.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("password")
        public _FinalStage password(@NotNull String password) {
            this.password = Objects.requireNonNull(password, "password must not be null");
            return this;
        }

        @java.lang.Override
        public BasicAuthDto build() {
            return new BasicAuthDto(username, password, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
