/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.Nullable;
import com.newscatcher.catchall.core.NullableNonemptyFilter;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CompanyAttributes.Builder.class)
public final class CompanyAttributes {
    private final Optional<String> domain;

    private final Optional<List<String>> keyPersons;

    private final Optional<List<String>> alternativeNames;

    private final Map<String, Object> additionalProperties;

    private CompanyAttributes(
            Optional<String> domain,
            Optional<List<String>> keyPersons,
            Optional<List<String>> alternativeNames,
            Map<String, Object> additionalProperties) {
        this.domain = domain;
        this.keyPersons = keyPersons;
        this.alternativeNames = alternativeNames;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Company website domain without protocol or trailing slash.
     * <p>The most reliable identifier — strongly recommended when available.</p>
     */
    @JsonIgnore
    public Optional<String> getDomain() {
        if (domain == null) {
            return Optional.empty();
        }
        return domain;
    }

    /**
     * @return Names of key people associated with the company (founders, executives, etc.). Improves matching for articles that mention people rather than the company name.
     */
    @JsonIgnore
    public Optional<List<String>> getKeyPersons() {
        if (keyPersons == null) {
            return Optional.empty();
        }
        return keyPersons;
    }

    /**
     * @return Alternative names, abbreviations, or aliases. Helps resolve common variations of the company name.
     */
    @JsonIgnore
    public Optional<List<String>> getAlternativeNames() {
        if (alternativeNames == null) {
            return Optional.empty();
        }
        return alternativeNames;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("domain")
    private Optional<String> _getDomain() {
        return domain;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("key_persons")
    private Optional<List<String>> _getKeyPersons() {
        return keyPersons;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("alternative_names")
    private Optional<List<String>> _getAlternativeNames() {
        return alternativeNames;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CompanyAttributes && equalTo((CompanyAttributes) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CompanyAttributes other) {
        return domain.equals(other.domain)
                && keyPersons.equals(other.keyPersons)
                && alternativeNames.equals(other.alternativeNames);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.domain, this.keyPersons, this.alternativeNames);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> domain = Optional.empty();

        private Optional<List<String>> keyPersons = Optional.empty();

        private Optional<List<String>> alternativeNames = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CompanyAttributes other) {
            domain(other.getDomain());
            keyPersons(other.getKeyPersons());
            alternativeNames(other.getAlternativeNames());
            return this;
        }

        /**
         * <p>Company website domain without protocol or trailing slash.</p>
         * <p>The most reliable identifier — strongly recommended when available.</p>
         */
        @JsonSetter(value = "domain", nulls = Nulls.SKIP)
        public Builder domain(Optional<String> domain) {
            this.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            this.domain = Optional.ofNullable(domain);
            return this;
        }

        public Builder domain(Nullable<String> domain) {
            if (domain.isNull()) {
                this.domain = null;
            } else if (domain.isEmpty()) {
                this.domain = Optional.empty();
            } else {
                this.domain = Optional.of(domain.get());
            }
            return this;
        }

        /**
         * <p>Names of key people associated with the company (founders, executives, etc.). Improves matching for articles that mention people rather than the company name.</p>
         */
        @JsonSetter(value = "key_persons", nulls = Nulls.SKIP)
        public Builder keyPersons(Optional<List<String>> keyPersons) {
            this.keyPersons = keyPersons;
            return this;
        }

        public Builder keyPersons(List<String> keyPersons) {
            this.keyPersons = Optional.ofNullable(keyPersons);
            return this;
        }

        public Builder keyPersons(Nullable<List<String>> keyPersons) {
            if (keyPersons.isNull()) {
                this.keyPersons = null;
            } else if (keyPersons.isEmpty()) {
                this.keyPersons = Optional.empty();
            } else {
                this.keyPersons = Optional.of(keyPersons.get());
            }
            return this;
        }

        /**
         * <p>Alternative names, abbreviations, or aliases. Helps resolve common variations of the company name.</p>
         */
        @JsonSetter(value = "alternative_names", nulls = Nulls.SKIP)
        public Builder alternativeNames(Optional<List<String>> alternativeNames) {
            this.alternativeNames = alternativeNames;
            return this;
        }

        public Builder alternativeNames(List<String> alternativeNames) {
            this.alternativeNames = Optional.ofNullable(alternativeNames);
            return this;
        }

        public Builder alternativeNames(Nullable<List<String>> alternativeNames) {
            if (alternativeNames.isNull()) {
                this.alternativeNames = null;
            } else if (alternativeNames.isEmpty()) {
                this.alternativeNames = Optional.empty();
            } else {
                this.alternativeNames = Optional.of(alternativeNames.get());
            }
            return this;
        }

        public CompanyAttributes build() {
            return new CompanyAttributes(domain, keyPersons, alternativeNames, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
