/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConnectedEntity.Builder.class)
public final class ConnectedEntity {
    private final String entityId;

    private final String name;

    private final int edScore;

    private final String relation;

    private final String type;

    private final Optional<CompanyAttributes> company;

    private final Map<String, Object> additionalProperties;

    private ConnectedEntity(
            String entityId,
            String name,
            int edScore,
            String relation,
            String type,
            Optional<CompanyAttributes> company,
            Map<String, Object> additionalProperties) {
        this.entityId = entityId;
        this.name = name;
        this.edScore = edScore;
        this.relation = relation;
        this.type = type;
        this.company = company;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier of the matched entity.
     */
    @JsonProperty("entity_id")
    public String getEntityId() {
        return entityId;
    }

    /**
     * @return Name of the matched entity.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Relevance score indicating how directly the entity is associated with this event.
     * <p>| Score | Meaning |
     * |-------|---------|
     * | 10 | Direct mention, critical event (merger, CEO change, major lawsuit) |
     * | 7–9 | Major impact (earnings, product launch, senior hire) |
     * | 4–6 | Routine update (minor product news, mid-level changes) |
     * | 1–3 | Indirect mention (listed with others, stock noise) |</p>
     */
    @JsonProperty("ed_score")
    public int getEdScore() {
        return edScore;
    }

    /**
     * @return Short explanation (up to 100 characters) of why this entity is associated with the event.
     */
    @JsonProperty("relation")
    public String getRelation() {
        return relation;
    }

    /**
     * @return The entity type.
     */
    @JsonProperty("type")
    public String getType() {
        return type;
    }

    /**
     * @return The stored attributes for this entity. Present only when attributes exist in the database.
     * <p>The field name matches the value of <code>type</code> — for example, <code>&quot;company&quot;</code> type entities have a <code>company</code>  field.</p>
     */
    @JsonProperty("company")
    public Optional<CompanyAttributes> getCompany() {
        return company;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectedEntity && equalTo((ConnectedEntity) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectedEntity other) {
        return entityId.equals(other.entityId)
                && name.equals(other.name)
                && edScore == other.edScore
                && relation.equals(other.relation)
                && type.equals(other.type)
                && company.equals(other.company);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.entityId, this.name, this.edScore, this.relation, this.type, this.company);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EntityIdStage builder() {
        return new Builder();
    }

    public interface EntityIdStage {
        /**
         * <p>Unique identifier of the matched entity.</p>
         */
        NameStage entityId(@NotNull String entityId);

        Builder from(ConnectedEntity other);
    }

    public interface NameStage {
        /**
         * <p>Name of the matched entity.</p>
         */
        EdScoreStage name(@NotNull String name);
    }

    public interface EdScoreStage {
        /**
         * <p>Relevance score indicating how directly the entity is associated with this event.</p>
         * <p>| Score | Meaning |
         * |-------|---------|
         * | 10 | Direct mention, critical event (merger, CEO change, major lawsuit) |
         * | 7–9 | Major impact (earnings, product launch, senior hire) |
         * | 4–6 | Routine update (minor product news, mid-level changes) |
         * | 1–3 | Indirect mention (listed with others, stock noise) |</p>
         */
        RelationStage edScore(int edScore);
    }

    public interface RelationStage {
        /**
         * <p>Short explanation (up to 100 characters) of why this entity is associated with the event.</p>
         */
        TypeStage relation(@NotNull String relation);
    }

    public interface TypeStage {
        /**
         * <p>The entity type.</p>
         */
        _FinalStage type(@NotNull String type);
    }

    public interface _FinalStage {
        ConnectedEntity build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The stored attributes for this entity. Present only when attributes exist in the database.</p>
         * <p>The field name matches the value of <code>type</code> — for example, <code>&quot;company&quot;</code> type entities have a <code>company</code>  field.</p>
         */
        _FinalStage company(Optional<CompanyAttributes> company);

        _FinalStage company(CompanyAttributes company);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements EntityIdStage, NameStage, EdScoreStage, RelationStage, TypeStage, _FinalStage {
        private String entityId;

        private String name;

        private int edScore;

        private String relation;

        private String type;

        private Optional<CompanyAttributes> company = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConnectedEntity other) {
            entityId(other.getEntityId());
            name(other.getName());
            edScore(other.getEdScore());
            relation(other.getRelation());
            type(other.getType());
            company(other.getCompany());
            return this;
        }

        /**
         * <p>Unique identifier of the matched entity.</p>
         * <p>Unique identifier of the matched entity.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("entity_id")
        public NameStage entityId(@NotNull String entityId) {
            this.entityId = Objects.requireNonNull(entityId, "entityId must not be null");
            return this;
        }

        /**
         * <p>Name of the matched entity.</p>
         * <p>Name of the matched entity.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public EdScoreStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Relevance score indicating how directly the entity is associated with this event.</p>
         * <p>| Score | Meaning |
         * |-------|---------|
         * | 10 | Direct mention, critical event (merger, CEO change, major lawsuit) |
         * | 7–9 | Major impact (earnings, product launch, senior hire) |
         * | 4–6 | Routine update (minor product news, mid-level changes) |
         * | 1–3 | Indirect mention (listed with others, stock noise) |</p>
         * <p>Relevance score indicating how directly the entity is associated with this event.</p>
         * <p>| Score | Meaning |
         * |-------|---------|
         * | 10 | Direct mention, critical event (merger, CEO change, major lawsuit) |
         * | 7–9 | Major impact (earnings, product launch, senior hire) |
         * | 4–6 | Routine update (minor product news, mid-level changes) |
         * | 1–3 | Indirect mention (listed with others, stock noise) |</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("ed_score")
        public RelationStage edScore(int edScore) {
            this.edScore = edScore;
            return this;
        }

        /**
         * <p>Short explanation (up to 100 characters) of why this entity is associated with the event.</p>
         * <p>Short explanation (up to 100 characters) of why this entity is associated with the event.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("relation")
        public TypeStage relation(@NotNull String relation) {
            this.relation = Objects.requireNonNull(relation, "relation must not be null");
            return this;
        }

        /**
         * <p>The entity type.</p>
         * <p>The entity type.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>The stored attributes for this entity. Present only when attributes exist in the database.</p>
         * <p>The field name matches the value of <code>type</code> — for example, <code>&quot;company&quot;</code> type entities have a <code>company</code>  field.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage company(CompanyAttributes company) {
            this.company = Optional.ofNullable(company);
            return this;
        }

        /**
         * <p>The stored attributes for this entity. Present only when attributes exist in the database.</p>
         * <p>The field name matches the value of <code>type</code> — for example, <code>&quot;company&quot;</code> type entities have a <code>company</code>  field.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "company", nulls = Nulls.SKIP)
        public _FinalStage company(Optional<CompanyAttributes> company) {
            this.company = company;
            return this;
        }

        @java.lang.Override
        public ConnectedEntity build() {
            return new ConnectedEntity(entityId, name, edScore, relation, type, company, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
