/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateEntityResponse.Builder.class)
public final class CreateEntityResponse {
    private final String id;

    private final String status;

    private final Map<String, Object> additionalProperties;

    private CreateEntityResponse(String id, String status, Map<String, Object> additionalProperties) {
        this.id = id;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier of the created entity.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Initial status of the entity. Always <code>pending</code> immediately after creation — enrichment happens asynchronously.
     */
    @JsonProperty("status")
    public String getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateEntityResponse && equalTo((CreateEntityResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateEntityResponse other) {
        return id.equals(other.id) && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Unique identifier of the created entity.</p>
         */
        StatusStage id(@NotNull String id);

        Builder from(CreateEntityResponse other);
    }

    public interface StatusStage {
        /**
         * <p>Initial status of the entity. Always <code>pending</code> immediately after creation — enrichment happens asynchronously.</p>
         */
        _FinalStage status(@NotNull String status);
    }

    public interface _FinalStage {
        CreateEntityResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, StatusStage, _FinalStage {
        private String id;

        private String status;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateEntityResponse other) {
            id(other.getId());
            status(other.getStatus());
            return this;
        }

        /**
         * <p>Unique identifier of the created entity.</p>
         * <p>Unique identifier of the created entity.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public StatusStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Initial status of the entity. Always <code>pending</code> immediately after creation — enrichment happens asynchronously.</p>
         * <p>Initial status of the entity. Always <code>pending</code> immediately after creation — enrichment happens asynchronously.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(@NotNull String status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        public CreateEntityResponse build() {
            return new CreateEntityResponse(id, status, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
