/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateProjectResponseDto.Builder.class)
public final class CreateProjectResponseDto {
    private final boolean success;

    private final String message;

    private final String projectId;

    private final String name;

    private final Map<String, Object> additionalProperties;

    private CreateProjectResponseDto(
            boolean success, String message, String projectId, String name, Map<String, Object> additionalProperties) {
        this.success = success;
        this.message = message;
        this.projectId = projectId;
        this.name = name;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return True if the operation succeeded; false otherwise.
     */
    @JsonProperty("success")
    public boolean getSuccess() {
        return success;
    }

    /**
     * @return Human-readable result message.
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    /**
     * @return Project identifier.
     */
    @JsonProperty("project_id")
    public String getProjectId() {
        return projectId;
    }

    /**
     * @return Name of the created project.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateProjectResponseDto && equalTo((CreateProjectResponseDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateProjectResponseDto other) {
        return success == other.success
                && message.equals(other.message)
                && projectId.equals(other.projectId)
                && name.equals(other.name);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.success, this.message, this.projectId, this.name);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SuccessStage builder() {
        return new Builder();
    }

    public interface SuccessStage {
        /**
         * <p>True if the operation succeeded; false otherwise.</p>
         */
        MessageStage success(boolean success);

        Builder from(CreateProjectResponseDto other);
    }

    public interface MessageStage {
        /**
         * <p>Human-readable result message.</p>
         */
        ProjectIdStage message(@NotNull String message);
    }

    public interface ProjectIdStage {
        /**
         * <p>Project identifier.</p>
         */
        NameStage projectId(@NotNull String projectId);
    }

    public interface NameStage {
        /**
         * <p>Name of the created project.</p>
         */
        _FinalStage name(@NotNull String name);
    }

    public interface _FinalStage {
        CreateProjectResponseDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SuccessStage, MessageStage, ProjectIdStage, NameStage, _FinalStage {
        private boolean success;

        private String message;

        private String projectId;

        private String name;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateProjectResponseDto other) {
            success(other.getSuccess());
            message(other.getMessage());
            projectId(other.getProjectId());
            name(other.getName());
            return this;
        }

        /**
         * <p>True if the operation succeeded; false otherwise.</p>
         * <p>True if the operation succeeded; false otherwise.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("success")
        public MessageStage success(boolean success) {
            this.success = success;
            return this;
        }

        /**
         * <p>Human-readable result message.</p>
         * <p>Human-readable result message.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public ProjectIdStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        /**
         * <p>Project identifier.</p>
         * <p>Project identifier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("project_id")
        public NameStage projectId(@NotNull String projectId) {
            this.projectId = Objects.requireNonNull(projectId, "projectId must not be null");
            return this;
        }

        /**
         * <p>Name of the created project.</p>
         * <p>Name of the created project.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        public CreateProjectResponseDto build() {
            return new CreateProjectResponseDto(success, message, projectId, name, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
