/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.Nullable;
import com.newscatcher.catchall.core.NullableNonemptyFilter;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeleteJobResponseDto.Builder.class)
public final class DeleteJobResponseDto {
    private final boolean success;

    private final Optional<String> message;

    private final Optional<String> jobId;

    private final Map<String, Object> additionalProperties;

    private DeleteJobResponseDto(
            boolean success,
            Optional<String> message,
            Optional<String> jobId,
            Map<String, Object> additionalProperties) {
        this.success = success;
        this.message = message;
        this.jobId = jobId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return True if the delete operation succeeded; false otherwise.
     */
    @JsonProperty("success")
    public boolean getSuccess() {
        return success;
    }

    /**
     * @return Human-readable result message.
     */
    @JsonIgnore
    public Optional<String> getMessage() {
        if (message == null) {
            return Optional.empty();
        }
        return message;
    }

    /**
     * @return ID of the deleted job. <code>null</code> on failure.
     */
    @JsonIgnore
    public Optional<String> getJobId() {
        if (jobId == null) {
            return Optional.empty();
        }
        return jobId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("message")
    private Optional<String> _getMessage() {
        return message;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("job_id")
    private Optional<String> _getJobId() {
        return jobId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeleteJobResponseDto && equalTo((DeleteJobResponseDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeleteJobResponseDto other) {
        return success == other.success && message.equals(other.message) && jobId.equals(other.jobId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.success, this.message, this.jobId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SuccessStage builder() {
        return new Builder();
    }

    public interface SuccessStage {
        /**
         * <p>True if the delete operation succeeded; false otherwise.</p>
         */
        _FinalStage success(boolean success);

        Builder from(DeleteJobResponseDto other);
    }

    public interface _FinalStage {
        DeleteJobResponseDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Human-readable result message.</p>
         */
        _FinalStage message(Optional<String> message);

        _FinalStage message(String message);

        _FinalStage message(Nullable<String> message);

        /**
         * <p>ID of the deleted job. <code>null</code> on failure.</p>
         */
        _FinalStage jobId(Optional<String> jobId);

        _FinalStage jobId(String jobId);

        _FinalStage jobId(Nullable<String> jobId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SuccessStage, _FinalStage {
        private boolean success;

        private Optional<String> jobId = Optional.empty();

        private Optional<String> message = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DeleteJobResponseDto other) {
            success(other.getSuccess());
            message(other.getMessage());
            jobId(other.getJobId());
            return this;
        }

        /**
         * <p>True if the delete operation succeeded; false otherwise.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("success")
        public _FinalStage success(boolean success) {
            this.success = success;
            return this;
        }

        /**
         * <p>ID of the deleted job. <code>null</code> on failure.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage jobId(Nullable<String> jobId) {
            if (jobId.isNull()) {
                this.jobId = null;
            } else if (jobId.isEmpty()) {
                this.jobId = Optional.empty();
            } else {
                this.jobId = Optional.of(jobId.get());
            }
            return this;
        }

        /**
         * <p>ID of the deleted job. <code>null</code> on failure.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage jobId(String jobId) {
            this.jobId = Optional.ofNullable(jobId);
            return this;
        }

        /**
         * <p>ID of the deleted job. <code>null</code> on failure.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "job_id", nulls = Nulls.SKIP)
        public _FinalStage jobId(Optional<String> jobId) {
            this.jobId = jobId;
            return this;
        }

        /**
         * <p>Human-readable result message.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage message(Nullable<String> message) {
            if (message.isNull()) {
                this.message = null;
            } else if (message.isEmpty()) {
                this.message = Optional.empty();
            } else {
                this.message = Optional.of(message.get());
            }
            return this;
        }

        /**
         * <p>Human-readable result message.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage message(String message) {
            this.message = Optional.ofNullable(message);
            return this;
        }

        /**
         * <p>Human-readable result message.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "message", nulls = Nulls.SKIP)
        public _FinalStage message(Optional<String> message) {
            this.message = message;
            return this;
        }

        @java.lang.Override
        public DeleteJobResponseDto build() {
            return new DeleteJobResponseDto(success, message, jobId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
