/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.Nullable;
import com.newscatcher.catchall.core.NullableNonemptyFilter;
import com.newscatcher.catchall.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EntityResponse.Builder.class)
public final class EntityResponse {
    private final String id;

    private final EntityType entityType;

    private final String organizationId;

    private final String name;

    private final Optional<String> description;

    private final Optional<String> externalEntityId;

    private final Optional<AdditionalAttributes> additionalAttributes;

    private final EntityStatus status;

    private final Optional<String> createdByUserId;

    private final Optional<OffsetDateTime> createdAt;

    private final Optional<OffsetDateTime> updatedAt;

    private final Map<String, Object> additionalProperties;

    private EntityResponse(
            String id,
            EntityType entityType,
            String organizationId,
            String name,
            Optional<String> description,
            Optional<String> externalEntityId,
            Optional<AdditionalAttributes> additionalAttributes,
            EntityStatus status,
            Optional<String> createdByUserId,
            Optional<OffsetDateTime> createdAt,
            Optional<OffsetDateTime> updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.entityType = entityType;
        this.organizationId = organizationId;
        this.name = name;
        this.description = description;
        this.externalEntityId = externalEntityId;
        this.additionalAttributes = additionalAttributes;
        this.status = status;
        this.createdByUserId = createdByUserId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier of the entity.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("entity_type")
    public EntityType getEntityType() {
        return entityType;
    }

    /**
     * @return Organization that owns this entity.
     */
    @JsonProperty("organization_id")
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * @return Entity name.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Free-text description.
     */
    @JsonIgnore
    public Optional<String> getDescription() {
        if (description == null) {
            return Optional.empty();
        }
        return description;
    }

    /**
     * @return External identifier for this entity. Null when not set.
     */
    @JsonIgnore
    public Optional<String> getExternalEntityId() {
        if (externalEntityId == null) {
            return Optional.empty();
        }
        return externalEntityId;
    }

    @JsonProperty("additional_attributes")
    public Optional<AdditionalAttributes> getAdditionalAttributes() {
        return additionalAttributes;
    }

    @JsonProperty("status")
    public EntityStatus getStatus() {
        return status;
    }

    /**
     * @return ID of the user who created this entity.
     */
    @JsonProperty("created_by_user_id")
    public Optional<String> getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * @return ISO 8601 timestamp of when the entity was created. Returned without timezone offset (server-local time).
     */
    @JsonProperty("created_at")
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    /**
     * @return ISO 8601 timestamp of when the entity was last updated. Returned without timezone offset (server-local time).
     */
    @JsonProperty("updated_at")
    public Optional<OffsetDateTime> getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("description")
    private Optional<String> _getDescription() {
        return description;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("external_entity_id")
    private Optional<String> _getExternalEntityId() {
        return externalEntityId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EntityResponse && equalTo((EntityResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EntityResponse other) {
        return id.equals(other.id)
                && entityType.equals(other.entityType)
                && organizationId.equals(other.organizationId)
                && name.equals(other.name)
                && description.equals(other.description)
                && externalEntityId.equals(other.externalEntityId)
                && additionalAttributes.equals(other.additionalAttributes)
                && status.equals(other.status)
                && createdByUserId.equals(other.createdByUserId)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.entityType,
                this.organizationId,
                this.name,
                this.description,
                this.externalEntityId,
                this.additionalAttributes,
                this.status,
                this.createdByUserId,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Unique identifier of the entity.</p>
         */
        EntityTypeStage id(@NotNull String id);

        Builder from(EntityResponse other);
    }

    public interface EntityTypeStage {
        OrganizationIdStage entityType(@NotNull EntityType entityType);
    }

    public interface OrganizationIdStage {
        /**
         * <p>Organization that owns this entity.</p>
         */
        NameStage organizationId(@NotNull String organizationId);
    }

    public interface NameStage {
        /**
         * <p>Entity name.</p>
         */
        StatusStage name(@NotNull String name);
    }

    public interface StatusStage {
        _FinalStage status(@NotNull EntityStatus status);
    }

    public interface _FinalStage {
        EntityResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Free-text description.</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        _FinalStage description(Nullable<String> description);

        /**
         * <p>External identifier for this entity. Null when not set.</p>
         */
        _FinalStage externalEntityId(Optional<String> externalEntityId);

        _FinalStage externalEntityId(String externalEntityId);

        _FinalStage externalEntityId(Nullable<String> externalEntityId);

        _FinalStage additionalAttributes(Optional<AdditionalAttributes> additionalAttributes);

        _FinalStage additionalAttributes(AdditionalAttributes additionalAttributes);

        /**
         * <p>ID of the user who created this entity.</p>
         */
        _FinalStage createdByUserId(Optional<String> createdByUserId);

        _FinalStage createdByUserId(String createdByUserId);

        /**
         * <p>ISO 8601 timestamp of when the entity was created. Returned without timezone offset (server-local time).</p>
         */
        _FinalStage createdAt(Optional<OffsetDateTime> createdAt);

        _FinalStage createdAt(OffsetDateTime createdAt);

        /**
         * <p>ISO 8601 timestamp of when the entity was last updated. Returned without timezone offset (server-local time).</p>
         */
        _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt);

        _FinalStage updatedAt(OffsetDateTime updatedAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, EntityTypeStage, OrganizationIdStage, NameStage, StatusStage, _FinalStage {
        private String id;

        private EntityType entityType;

        private String organizationId;

        private String name;

        private EntityStatus status;

        private Optional<OffsetDateTime> updatedAt = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        private Optional<String> createdByUserId = Optional.empty();

        private Optional<AdditionalAttributes> additionalAttributes = Optional.empty();

        private Optional<String> externalEntityId = Optional.empty();

        private Optional<String> description = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EntityResponse other) {
            id(other.getId());
            entityType(other.getEntityType());
            organizationId(other.getOrganizationId());
            name(other.getName());
            description(other.getDescription());
            externalEntityId(other.getExternalEntityId());
            additionalAttributes(other.getAdditionalAttributes());
            status(other.getStatus());
            createdByUserId(other.getCreatedByUserId());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>Unique identifier of the entity.</p>
         * <p>Unique identifier of the entity.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public EntityTypeStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("entity_type")
        public OrganizationIdStage entityType(@NotNull EntityType entityType) {
            this.entityType = Objects.requireNonNull(entityType, "entityType must not be null");
            return this;
        }

        /**
         * <p>Organization that owns this entity.</p>
         * <p>Organization that owns this entity.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("organization_id")
        public NameStage organizationId(@NotNull String organizationId) {
            this.organizationId = Objects.requireNonNull(organizationId, "organizationId must not be null");
            return this;
        }

        /**
         * <p>Entity name.</p>
         * <p>Entity name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public StatusStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(@NotNull EntityStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>ISO 8601 timestamp of when the entity was last updated. Returned without timezone offset (server-local time).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage updatedAt(OffsetDateTime updatedAt) {
            this.updatedAt = Optional.ofNullable(updatedAt);
            return this;
        }

        /**
         * <p>ISO 8601 timestamp of when the entity was last updated. Returned without timezone offset (server-local time).</p>
         */
        @java.lang.Override
        @JsonSetter(value = "updated_at", nulls = Nulls.SKIP)
        public _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * <p>ISO 8601 timestamp of when the entity was created. Returned without timezone offset (server-local time).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>ISO 8601 timestamp of when the entity was created. Returned without timezone offset (server-local time).</p>
         */
        @java.lang.Override
        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public _FinalStage createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * <p>ID of the user who created this entity.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createdByUserId(String createdByUserId) {
            this.createdByUserId = Optional.ofNullable(createdByUserId);
            return this;
        }

        /**
         * <p>ID of the user who created this entity.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "created_by_user_id", nulls = Nulls.SKIP)
        public _FinalStage createdByUserId(Optional<String> createdByUserId) {
            this.createdByUserId = createdByUserId;
            return this;
        }

        @java.lang.Override
        public _FinalStage additionalAttributes(AdditionalAttributes additionalAttributes) {
            this.additionalAttributes = Optional.ofNullable(additionalAttributes);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "additional_attributes", nulls = Nulls.SKIP)
        public _FinalStage additionalAttributes(Optional<AdditionalAttributes> additionalAttributes) {
            this.additionalAttributes = additionalAttributes;
            return this;
        }

        /**
         * <p>External identifier for this entity. Null when not set.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalEntityId(Nullable<String> externalEntityId) {
            if (externalEntityId.isNull()) {
                this.externalEntityId = null;
            } else if (externalEntityId.isEmpty()) {
                this.externalEntityId = Optional.empty();
            } else {
                this.externalEntityId = Optional.of(externalEntityId.get());
            }
            return this;
        }

        /**
         * <p>External identifier for this entity. Null when not set.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalEntityId(String externalEntityId) {
            this.externalEntityId = Optional.ofNullable(externalEntityId);
            return this;
        }

        /**
         * <p>External identifier for this entity. Null when not set.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "external_entity_id", nulls = Nulls.SKIP)
        public _FinalStage externalEntityId(Optional<String> externalEntityId) {
            this.externalEntityId = externalEntityId;
            return this;
        }

        /**
         * <p>Free-text description.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(Nullable<String> description) {
            if (description.isNull()) {
                this.description = null;
            } else if (description.isEmpty()) {
                this.description = Optional.empty();
            } else {
                this.description = Optional.of(description.get());
            }
            return this;
        }

        /**
         * <p>Free-text description.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Free-text description.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public EntityResponse build() {
            return new EntityResponse(
                    id,
                    entityType,
                    organizationId,
                    name,
                    description,
                    externalEntityId,
                    additionalAttributes,
                    status,
                    createdByUserId,
                    createdAt,
                    updatedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
