/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EntityStatus {
    public static final EntityStatus FAILED = new EntityStatus(Value.FAILED, "failed");

    public static final EntityStatus PENDING = new EntityStatus(Value.PENDING, "pending");

    public static final EntityStatus ENRICHING = new EntityStatus(Value.ENRICHING, "enriching");

    public static final EntityStatus READY = new EntityStatus(Value.READY, "ready");

    private final Value value;

    private final String string;

    EntityStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof EntityStatus && this.string.equals(((EntityStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case FAILED:
                return visitor.visitFailed();
            case PENDING:
                return visitor.visitPending();
            case ENRICHING:
                return visitor.visitEnriching();
            case READY:
                return visitor.visitReady();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EntityStatus valueOf(String value) {
        switch (value) {
            case "failed":
                return FAILED;
            case "pending":
                return PENDING;
            case "enriching":
                return ENRICHING;
            case "ready":
                return READY;
            default:
                return new EntityStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PENDING,

        ENRICHING,

        READY,

        FAILED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPending();

        T visitEnriching();

        T visitReady();

        T visitFailed();

        T visitUnknown(String unknownType);
    }
}
