/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EntityAssociationType {
    public static final EntityAssociationType EVENT_ASSOCIATED =
            new EntityAssociationType(Value.EVENT_ASSOCIATED, "event_associated");

    public static final EntityAssociationType MENTION = new EntityAssociationType(Value.MENTION, "mention");

    private final Value value;

    private final String string;

    EntityAssociationType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof EntityAssociationType
                        && this.string.equals(((EntityAssociationType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case EVENT_ASSOCIATED:
                return visitor.visitEventAssociated();
            case MENTION:
                return visitor.visitMention();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EntityAssociationType valueOf(String value) {
        switch (value) {
            case "event_associated":
                return EVENT_ASSOCIATED;
            case "mention":
                return MENTION;
            default:
                return new EntityAssociationType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        MENTION,

        EVENT_ASSOCIATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitMention();

        T visitEventAssociated();

        T visitUnknown(String unknownType);
    }
}
