/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class HttpMethod {
    public static final HttpMethod GET = new HttpMethod(Value.GET, "GET");

    public static final HttpMethod PUT = new HttpMethod(Value.PUT, "PUT");

    public static final HttpMethod PATCH = new HttpMethod(Value.PATCH, "PATCH");

    public static final HttpMethod DELETE = new HttpMethod(Value.DELETE, "DELETE");

    public static final HttpMethod POST = new HttpMethod(Value.POST, "POST");

    private final Value value;

    private final String string;

    HttpMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof HttpMethod && this.string.equals(((HttpMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case GET:
                return visitor.visitGet();
            case PUT:
                return visitor.visitPut();
            case PATCH:
                return visitor.visitPatch();
            case DELETE:
                return visitor.visitDelete();
            case POST:
                return visitor.visitPost();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static HttpMethod valueOf(String value) {
        switch (value) {
            case "GET":
                return GET;
            case "PUT":
                return PUT;
            case "PATCH":
                return PATCH;
            case "DELETE":
                return DELETE;
            case "POST":
                return POST;
            default:
                return new HttpMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        GET,

        POST,

        PUT,

        PATCH,

        DELETE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitGet();

        T visitPost();

        T visitPut();

        T visitPatch();

        T visitDelete();

        T visitUnknown(String unknownType);
    }
}
