/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.Nullable;
import com.newscatcher.catchall.core.NullableNonemptyFilter;
import com.newscatcher.catchall.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InitializeResponseDto.Builder.class)
public final class InitializeResponseDto {
    private final String query;

    private final Optional<String> context;

    private final List<ValidatorSchema> validators;

    private final List<EnrichmentSchema> enrichments;

    private final Optional<OffsetDateTime> startDate;

    private final Optional<OffsetDateTime> endDate;

    private final Optional<List<String>> dateModificationMessage;

    private final Map<String, Object> additionalProperties;

    private InitializeResponseDto(
            String query,
            Optional<String> context,
            List<ValidatorSchema> validators,
            List<EnrichmentSchema> enrichments,
            Optional<OffsetDateTime> startDate,
            Optional<OffsetDateTime> endDate,
            Optional<List<String>> dateModificationMessage,
            Map<String, Object> additionalProperties) {
        this.query = query;
        this.context = context;
        this.validators = validators;
        this.enrichments = enrichments;
        this.startDate = startDate;
        this.endDate = endDate;
        this.dateModificationMessage = dateModificationMessage;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Echo of the query from the request.
     */
    @JsonProperty("query")
    public String getQuery() {
        return query;
    }

    /**
     * @return Echo of the context from the request. Null if not provided.
     */
    @JsonIgnore
    public Optional<String> getContext() {
        if (context == null) {
            return Optional.empty();
        }
        return context;
    }

    /**
     * @return Suggested validators for filtering relevant web pages.
     */
    @JsonProperty("validators")
    public List<ValidatorSchema> getValidators() {
        return validators;
    }

    /**
     * @return Suggested enrichment fields for data extraction.
     */
    @JsonProperty("enrichments")
    public List<EnrichmentSchema> getEnrichments() {
        return enrichments;
    }

    @JsonProperty("start_date")
    public Optional<OffsetDateTime> getStartDate() {
        return startDate;
    }

    @JsonProperty("end_date")
    public Optional<OffsetDateTime> getEndDate() {
        return endDate;
    }

    /**
     * @return Messages explaining date adjustments due to plan limits.
     * <p>Empty array if no modifications were needed. Contains human-readable messages when requested dates exceed plan's allowed lookback period.</p>
     */
    @JsonProperty("date_modification_message")
    public Optional<List<String>> getDateModificationMessage() {
        return dateModificationMessage;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("context")
    private Optional<String> _getContext() {
        return context;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InitializeResponseDto && equalTo((InitializeResponseDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InitializeResponseDto other) {
        return query.equals(other.query)
                && context.equals(other.context)
                && validators.equals(other.validators)
                && enrichments.equals(other.enrichments)
                && startDate.equals(other.startDate)
                && endDate.equals(other.endDate)
                && dateModificationMessage.equals(other.dateModificationMessage);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.query,
                this.context,
                this.validators,
                this.enrichments,
                this.startDate,
                this.endDate,
                this.dateModificationMessage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static QueryStage builder() {
        return new Builder();
    }

    public interface QueryStage {
        /**
         * <p>Echo of the query from the request.</p>
         */
        _FinalStage query(@NotNull String query);

        Builder from(InitializeResponseDto other);
    }

    public interface _FinalStage {
        InitializeResponseDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Echo of the context from the request. Null if not provided.</p>
         */
        _FinalStage context(Optional<String> context);

        _FinalStage context(String context);

        _FinalStage context(Nullable<String> context);

        /**
         * <p>Suggested validators for filtering relevant web pages.</p>
         */
        _FinalStage validators(List<ValidatorSchema> validators);

        _FinalStage addValidators(ValidatorSchema validators);

        _FinalStage addAllValidators(List<ValidatorSchema> validators);

        /**
         * <p>Suggested enrichment fields for data extraction.</p>
         */
        _FinalStage enrichments(List<EnrichmentSchema> enrichments);

        _FinalStage addEnrichments(EnrichmentSchema enrichments);

        _FinalStage addAllEnrichments(List<EnrichmentSchema> enrichments);

        _FinalStage startDate(Optional<OffsetDateTime> startDate);

        _FinalStage startDate(OffsetDateTime startDate);

        _FinalStage endDate(Optional<OffsetDateTime> endDate);

        _FinalStage endDate(OffsetDateTime endDate);

        /**
         * <p>Messages explaining date adjustments due to plan limits.</p>
         * <p>Empty array if no modifications were needed. Contains human-readable messages when requested dates exceed plan's allowed lookback period.</p>
         */
        _FinalStage dateModificationMessage(Optional<List<String>> dateModificationMessage);

        _FinalStage dateModificationMessage(List<String> dateModificationMessage);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements QueryStage, _FinalStage {
        private String query;

        private Optional<List<String>> dateModificationMessage = Optional.empty();

        private Optional<OffsetDateTime> endDate = Optional.empty();

        private Optional<OffsetDateTime> startDate = Optional.empty();

        private List<EnrichmentSchema> enrichments = new ArrayList<>();

        private List<ValidatorSchema> validators = new ArrayList<>();

        private Optional<String> context = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InitializeResponseDto other) {
            query(other.getQuery());
            context(other.getContext());
            validators(other.getValidators());
            enrichments(other.getEnrichments());
            startDate(other.getStartDate());
            endDate(other.getEndDate());
            dateModificationMessage(other.getDateModificationMessage());
            return this;
        }

        /**
         * <p>Echo of the query from the request.</p>
         * <p>Echo of the query from the request.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("query")
        public _FinalStage query(@NotNull String query) {
            this.query = Objects.requireNonNull(query, "query must not be null");
            return this;
        }

        /**
         * <p>Messages explaining date adjustments due to plan limits.</p>
         * <p>Empty array if no modifications were needed. Contains human-readable messages when requested dates exceed plan's allowed lookback period.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage dateModificationMessage(List<String> dateModificationMessage) {
            this.dateModificationMessage = Optional.ofNullable(dateModificationMessage);
            return this;
        }

        /**
         * <p>Messages explaining date adjustments due to plan limits.</p>
         * <p>Empty array if no modifications were needed. Contains human-readable messages when requested dates exceed plan's allowed lookback period.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "date_modification_message", nulls = Nulls.SKIP)
        public _FinalStage dateModificationMessage(Optional<List<String>> dateModificationMessage) {
            this.dateModificationMessage = dateModificationMessage;
            return this;
        }

        @java.lang.Override
        public _FinalStage endDate(OffsetDateTime endDate) {
            this.endDate = Optional.ofNullable(endDate);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "end_date", nulls = Nulls.SKIP)
        public _FinalStage endDate(Optional<OffsetDateTime> endDate) {
            this.endDate = endDate;
            return this;
        }

        @java.lang.Override
        public _FinalStage startDate(OffsetDateTime startDate) {
            this.startDate = Optional.ofNullable(startDate);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "start_date", nulls = Nulls.SKIP)
        public _FinalStage startDate(Optional<OffsetDateTime> startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * <p>Suggested enrichment fields for data extraction.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllEnrichments(List<EnrichmentSchema> enrichments) {
            if (enrichments != null) {
                this.enrichments.addAll(enrichments);
            }
            return this;
        }

        /**
         * <p>Suggested enrichment fields for data extraction.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addEnrichments(EnrichmentSchema enrichments) {
            this.enrichments.add(enrichments);
            return this;
        }

        /**
         * <p>Suggested enrichment fields for data extraction.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "enrichments", nulls = Nulls.SKIP)
        public _FinalStage enrichments(List<EnrichmentSchema> enrichments) {
            this.enrichments.clear();
            if (enrichments != null) {
                this.enrichments.addAll(enrichments);
            }
            return this;
        }

        /**
         * <p>Suggested validators for filtering relevant web pages.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllValidators(List<ValidatorSchema> validators) {
            if (validators != null) {
                this.validators.addAll(validators);
            }
            return this;
        }

        /**
         * <p>Suggested validators for filtering relevant web pages.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addValidators(ValidatorSchema validators) {
            this.validators.add(validators);
            return this;
        }

        /**
         * <p>Suggested validators for filtering relevant web pages.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "validators", nulls = Nulls.SKIP)
        public _FinalStage validators(List<ValidatorSchema> validators) {
            this.validators.clear();
            if (validators != null) {
                this.validators.addAll(validators);
            }
            return this;
        }

        /**
         * <p>Echo of the context from the request. Null if not provided.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage context(Nullable<String> context) {
            if (context.isNull()) {
                this.context = null;
            } else if (context.isEmpty()) {
                this.context = Optional.empty();
            } else {
                this.context = Optional.of(context.get());
            }
            return this;
        }

        /**
         * <p>Echo of the context from the request. Null if not provided.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage context(String context) {
            this.context = Optional.ofNullable(context);
            return this;
        }

        /**
         * <p>Echo of the context from the request. Null if not provided.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "context", nulls = Nulls.SKIP)
        public _FinalStage context(Optional<String> context) {
            this.context = context;
            return this;
        }

        @java.lang.Override
        public InitializeResponseDto build() {
            return new InitializeResponseDto(
                    query,
                    context,
                    validators,
                    enrichments,
                    startDate,
                    endDate,
                    dateModificationMessage,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
