/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class JobStatus {
    public static final JobStatus FAILED = new JobStatus(Value.FAILED, "failed");

    public static final JobStatus COMPLETED = new JobStatus(Value.COMPLETED, "completed");

    public static final JobStatus CLUSTERING = new JobStatus(Value.CLUSTERING, "clustering");

    public static final JobStatus SUBMITTED = new JobStatus(Value.SUBMITTED, "submitted");

    public static final JobStatus ENRICHING = new JobStatus(Value.ENRICHING, "enriching");

    public static final JobStatus ANALYZING = new JobStatus(Value.ANALYZING, "analyzing");

    public static final JobStatus FETCHING = new JobStatus(Value.FETCHING, "fetching");

    private final Value value;

    private final String string;

    JobStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof JobStatus && this.string.equals(((JobStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case FAILED:
                return visitor.visitFailed();
            case COMPLETED:
                return visitor.visitCompleted();
            case CLUSTERING:
                return visitor.visitClustering();
            case SUBMITTED:
                return visitor.visitSubmitted();
            case ENRICHING:
                return visitor.visitEnriching();
            case ANALYZING:
                return visitor.visitAnalyzing();
            case FETCHING:
                return visitor.visitFetching();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static JobStatus valueOf(String value) {
        switch (value) {
            case "failed":
                return FAILED;
            case "completed":
                return COMPLETED;
            case "clustering":
                return CLUSTERING;
            case "submitted":
                return SUBMITTED;
            case "enriching":
                return ENRICHING;
            case "analyzing":
                return ANALYZING;
            case "fetching":
                return FETCHING;
            default:
                return new JobStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SUBMITTED,

        ANALYZING,

        FETCHING,

        CLUSTERING,

        ENRICHING,

        COMPLETED,

        FAILED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSubmitted();

        T visitAnalyzing();

        T visitFetching();

        T visitClustering();

        T visitEnriching();

        T visitCompleted();

        T visitFailed();

        T visitUnknown(String unknownType);
    }
}
