/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListUserJobsResponseDto.Builder.class)
public final class ListUserJobsResponseDto {
    private final String jobId;

    private final String query;

    private final OffsetDateTime createdAt;

    private final String status;

    private final Map<String, Object> additionalProperties;

    private ListUserJobsResponseDto(
            String jobId,
            String query,
            OffsetDateTime createdAt,
            String status,
            Map<String, Object> additionalProperties) {
        this.jobId = jobId;
        this.query = query;
        this.createdAt = createdAt;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Job identifier.
     */
    @JsonProperty("job_id")
    public String getJobId() {
        return jobId;
    }

    /**
     * @return The natural language query for this job.
     */
    @JsonProperty("query")
    public String getQuery() {
        return query;
    }

    /**
     * @return Job creation timestamp in ISO 8601 format.
     */
    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Current processing status of the job.
     */
    @JsonProperty("status")
    public String getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListUserJobsResponseDto && equalTo((ListUserJobsResponseDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListUserJobsResponseDto other) {
        return jobId.equals(other.jobId)
                && query.equals(other.query)
                && createdAt.equals(other.createdAt)
                && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.jobId, this.query, this.createdAt, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static JobIdStage builder() {
        return new Builder();
    }

    public interface JobIdStage {
        /**
         * <p>Job identifier.</p>
         */
        QueryStage jobId(@NotNull String jobId);

        Builder from(ListUserJobsResponseDto other);
    }

    public interface QueryStage {
        /**
         * <p>The natural language query for this job.</p>
         */
        CreatedAtStage query(@NotNull String query);
    }

    public interface CreatedAtStage {
        /**
         * <p>Job creation timestamp in ISO 8601 format.</p>
         */
        StatusStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface StatusStage {
        /**
         * <p>Current processing status of the job.</p>
         */
        _FinalStage status(@NotNull String status);
    }

    public interface _FinalStage {
        ListUserJobsResponseDto build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements JobIdStage, QueryStage, CreatedAtStage, StatusStage, _FinalStage {
        private String jobId;

        private String query;

        private OffsetDateTime createdAt;

        private String status;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListUserJobsResponseDto other) {
            jobId(other.getJobId());
            query(other.getQuery());
            createdAt(other.getCreatedAt());
            status(other.getStatus());
            return this;
        }

        /**
         * <p>Job identifier.</p>
         * <p>Job identifier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("job_id")
        public QueryStage jobId(@NotNull String jobId) {
            this.jobId = Objects.requireNonNull(jobId, "jobId must not be null");
            return this;
        }

        /**
         * <p>The natural language query for this job.</p>
         * <p>The natural language query for this job.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("query")
        public CreatedAtStage query(@NotNull String query) {
            this.query = Objects.requireNonNull(query, "query must not be null");
            return this;
        }

        /**
         * <p>Job creation timestamp in ISO 8601 format.</p>
         * <p>Job creation timestamp in ISO 8601 format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public StatusStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Current processing status of the job.</p>
         * <p>Current processing status of the job.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(@NotNull String status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        public ListUserJobsResponseDto build() {
            return new ListUserJobsResponseDto(jobId, query, createdAt, status, additionalProperties);
        }
    }
}
