/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MonitorCitation.Builder.class)
public final class MonitorCitation {
    private final String id;

    private final String title;

    private final String link;

    private final OffsetDateTime publishedDate;

    private final String jobId;

    private final OffsetDateTime addedOn;

    private final Map<String, Object> additionalProperties;

    private MonitorCitation(
            String id,
            String title,
            String link,
            OffsetDateTime publishedDate,
            String jobId,
            OffsetDateTime addedOn,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.title = title;
        this.link = link;
        this.publishedDate = publishedDate;
        this.jobId = jobId;
        this.addedOn = addedOn;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Article identifier from News API v3
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Article title
     */
    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    /**
     * @return URL to the source article
     */
    @JsonProperty("link")
    public String getLink() {
        return link;
    }

    /**
     * @return Article publication date in ISO 8601 format with UTC timezone.
     */
    @JsonProperty("published_date")
    public OffsetDateTime getPublishedDate() {
        return publishedDate;
    }

    /**
     * @return Job ID that found this citation.
     */
    @JsonProperty("job_id")
    public String getJobId() {
        return jobId;
    }

    /**
     * @return The date when the citation was added to the record in ISO 8601 format with UTC timezone.
     */
    @JsonProperty("added_on")
    public OffsetDateTime getAddedOn() {
        return addedOn;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MonitorCitation && equalTo((MonitorCitation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MonitorCitation other) {
        return id.equals(other.id)
                && title.equals(other.title)
                && link.equals(other.link)
                && publishedDate.equals(other.publishedDate)
                && jobId.equals(other.jobId)
                && addedOn.equals(other.addedOn);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.title, this.link, this.publishedDate, this.jobId, this.addedOn);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Article identifier from News API v3</p>
         */
        TitleStage id(@NotNull String id);

        Builder from(MonitorCitation other);
    }

    public interface TitleStage {
        /**
         * <p>Article title</p>
         */
        LinkStage title(@NotNull String title);
    }

    public interface LinkStage {
        /**
         * <p>URL to the source article</p>
         */
        PublishedDateStage link(@NotNull String link);
    }

    public interface PublishedDateStage {
        /**
         * <p>Article publication date in ISO 8601 format with UTC timezone.</p>
         */
        JobIdStage publishedDate(@NotNull OffsetDateTime publishedDate);
    }

    public interface JobIdStage {
        /**
         * <p>Job ID that found this citation.</p>
         */
        AddedOnStage jobId(@NotNull String jobId);
    }

    public interface AddedOnStage {
        /**
         * <p>The date when the citation was added to the record in ISO 8601 format with UTC timezone.</p>
         */
        _FinalStage addedOn(@NotNull OffsetDateTime addedOn);
    }

    public interface _FinalStage {
        MonitorCitation build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, TitleStage, LinkStage, PublishedDateStage, JobIdStage, AddedOnStage, _FinalStage {
        private String id;

        private String title;

        private String link;

        private OffsetDateTime publishedDate;

        private String jobId;

        private OffsetDateTime addedOn;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MonitorCitation other) {
            id(other.getId());
            title(other.getTitle());
            link(other.getLink());
            publishedDate(other.getPublishedDate());
            jobId(other.getJobId());
            addedOn(other.getAddedOn());
            return this;
        }

        /**
         * <p>Article identifier from News API v3</p>
         * <p>Article identifier from News API v3</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public TitleStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Article title</p>
         * <p>Article title</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("title")
        public LinkStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        /**
         * <p>URL to the source article</p>
         * <p>URL to the source article</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("link")
        public PublishedDateStage link(@NotNull String link) {
            this.link = Objects.requireNonNull(link, "link must not be null");
            return this;
        }

        /**
         * <p>Article publication date in ISO 8601 format with UTC timezone.</p>
         * <p>Article publication date in ISO 8601 format with UTC timezone.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("published_date")
        public JobIdStage publishedDate(@NotNull OffsetDateTime publishedDate) {
            this.publishedDate = Objects.requireNonNull(publishedDate, "publishedDate must not be null");
            return this;
        }

        /**
         * <p>Job ID that found this citation.</p>
         * <p>Job ID that found this citation.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("job_id")
        public AddedOnStage jobId(@NotNull String jobId) {
            this.jobId = Objects.requireNonNull(jobId, "jobId must not be null");
            return this;
        }

        /**
         * <p>The date when the citation was added to the record in ISO 8601 format with UTC timezone.</p>
         * <p>The date when the citation was added to the record in ISO 8601 format with UTC timezone.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("added_on")
        public _FinalStage addedOn(@NotNull OffsetDateTime addedOn) {
            this.addedOn = Objects.requireNonNull(addedOn, "addedOn must not be null");
            return this;
        }

        @java.lang.Override
        public MonitorCitation build() {
            return new MonitorCitation(id, title, link, publishedDate, jobId, addedOn, additionalProperties);
        }
    }
}
