/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MonitorRecord.Builder.class)
public final class MonitorRecord {
    private final String recordId;

    private final String recordTitle;

    private final Map<String, Object> enrichment;

    private final List<MonitorCitation> citations;

    private final Optional<OffsetDateTime> addedOn;

    private final Optional<OffsetDateTime> updatedOn;

    private final Map<String, Object> additionalProperties;

    private MonitorRecord(
            String recordId,
            String recordTitle,
            Map<String, Object> enrichment,
            List<MonitorCitation> citations,
            Optional<OffsetDateTime> addedOn,
            Optional<OffsetDateTime> updatedOn,
            Map<String, Object> additionalProperties) {
        this.recordId = recordId;
        this.recordTitle = recordTitle;
        this.enrichment = enrichment;
        this.citations = citations;
        this.addedOn = addedOn;
        this.updatedOn = updatedOn;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier for the record.
     */
    @JsonProperty("record_id")
    public String getRecordId() {
        return recordId;
    }

    /**
     * @return Short title summarizing the record.
     */
    @JsonProperty("record_title")
    public String getRecordTitle() {
        return recordTitle;
    }

    /**
     * @return Structured data extracted from articles. Schema is dynamically generated per job. Field names are chosen semantically to match the content.
     * <p>See <a href="https://www.newscatcherapi.com/docs/v3/catch-all/overview/dynamic-schemas">Understanding dynamic schemas</a> for integration guidance.</p>
     */
    @JsonProperty("enrichment")
    public Map<String, Object> getEnrichment() {
        return enrichment;
    }

    /**
     * @return Source articles with monitor-specific metadata (job_id, added_on timestamps).
     */
    @JsonProperty("citations")
    public List<MonitorCitation> getCitations() {
        return citations;
    }

    /**
     * @return The date when this record was first added to monitor results in ISO 8601 format with UTC timezone.
     */
    @JsonProperty("added_on")
    public Optional<OffsetDateTime> getAddedOn() {
        return addedOn;
    }

    /**
     * @return The date when this record was last updated in monitor results in ISO 8601 format with UTC timezone.
     */
    @JsonProperty("updated_on")
    public Optional<OffsetDateTime> getUpdatedOn() {
        return updatedOn;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MonitorRecord && equalTo((MonitorRecord) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MonitorRecord other) {
        return recordId.equals(other.recordId)
                && recordTitle.equals(other.recordTitle)
                && enrichment.equals(other.enrichment)
                && citations.equals(other.citations)
                && addedOn.equals(other.addedOn)
                && updatedOn.equals(other.updatedOn);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.recordId, this.recordTitle, this.enrichment, this.citations, this.addedOn, this.updatedOn);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RecordIdStage builder() {
        return new Builder();
    }

    public interface RecordIdStage {
        /**
         * <p>Unique identifier for the record.</p>
         */
        RecordTitleStage recordId(@NotNull String recordId);

        Builder from(MonitorRecord other);
    }

    public interface RecordTitleStage {
        /**
         * <p>Short title summarizing the record.</p>
         */
        _FinalStage recordTitle(@NotNull String recordTitle);
    }

    public interface _FinalStage {
        MonitorRecord build();

        /**
         * <p>Structured data extracted from articles. Schema is dynamically generated per job. Field names are chosen semantically to match the content.</p>
         * <p>See <a href="https://www.newscatcherapi.com/docs/v3/catch-all/overview/dynamic-schemas">Understanding dynamic schemas</a> for integration guidance.</p>
         */
        _FinalStage enrichment(Map<String, Object> enrichment);

        _FinalStage putAllEnrichment(Map<String, Object> enrichment);

        _FinalStage enrichment(String key, Object value);

        /**
         * <p>Source articles with monitor-specific metadata (job_id, added_on timestamps).</p>
         */
        _FinalStage citations(List<MonitorCitation> citations);

        _FinalStage addCitations(MonitorCitation citations);

        _FinalStage addAllCitations(List<MonitorCitation> citations);

        /**
         * <p>The date when this record was first added to monitor results in ISO 8601 format with UTC timezone.</p>
         */
        _FinalStage addedOn(Optional<OffsetDateTime> addedOn);

        _FinalStage addedOn(OffsetDateTime addedOn);

        /**
         * <p>The date when this record was last updated in monitor results in ISO 8601 format with UTC timezone.</p>
         */
        _FinalStage updatedOn(Optional<OffsetDateTime> updatedOn);

        _FinalStage updatedOn(OffsetDateTime updatedOn);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements RecordIdStage, RecordTitleStage, _FinalStage {
        private String recordId;

        private String recordTitle;

        private Optional<OffsetDateTime> updatedOn = Optional.empty();

        private Optional<OffsetDateTime> addedOn = Optional.empty();

        private List<MonitorCitation> citations = new ArrayList<>();

        private Map<String, Object> enrichment = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MonitorRecord other) {
            recordId(other.getRecordId());
            recordTitle(other.getRecordTitle());
            enrichment(other.getEnrichment());
            citations(other.getCitations());
            addedOn(other.getAddedOn());
            updatedOn(other.getUpdatedOn());
            return this;
        }

        /**
         * <p>Unique identifier for the record.</p>
         * <p>Unique identifier for the record.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("record_id")
        public RecordTitleStage recordId(@NotNull String recordId) {
            this.recordId = Objects.requireNonNull(recordId, "recordId must not be null");
            return this;
        }

        /**
         * <p>Short title summarizing the record.</p>
         * <p>Short title summarizing the record.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("record_title")
        public _FinalStage recordTitle(@NotNull String recordTitle) {
            this.recordTitle = Objects.requireNonNull(recordTitle, "recordTitle must not be null");
            return this;
        }

        /**
         * <p>The date when this record was last updated in monitor results in ISO 8601 format with UTC timezone.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage updatedOn(OffsetDateTime updatedOn) {
            this.updatedOn = Optional.ofNullable(updatedOn);
            return this;
        }

        /**
         * <p>The date when this record was last updated in monitor results in ISO 8601 format with UTC timezone.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "updated_on", nulls = Nulls.SKIP)
        public _FinalStage updatedOn(Optional<OffsetDateTime> updatedOn) {
            this.updatedOn = updatedOn;
            return this;
        }

        /**
         * <p>The date when this record was first added to monitor results in ISO 8601 format with UTC timezone.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addedOn(OffsetDateTime addedOn) {
            this.addedOn = Optional.ofNullable(addedOn);
            return this;
        }

        /**
         * <p>The date when this record was first added to monitor results in ISO 8601 format with UTC timezone.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "added_on", nulls = Nulls.SKIP)
        public _FinalStage addedOn(Optional<OffsetDateTime> addedOn) {
            this.addedOn = addedOn;
            return this;
        }

        /**
         * <p>Source articles with monitor-specific metadata (job_id, added_on timestamps).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllCitations(List<MonitorCitation> citations) {
            if (citations != null) {
                this.citations.addAll(citations);
            }
            return this;
        }

        /**
         * <p>Source articles with monitor-specific metadata (job_id, added_on timestamps).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addCitations(MonitorCitation citations) {
            this.citations.add(citations);
            return this;
        }

        /**
         * <p>Source articles with monitor-specific metadata (job_id, added_on timestamps).</p>
         */
        @java.lang.Override
        @JsonSetter(value = "citations", nulls = Nulls.SKIP)
        public _FinalStage citations(List<MonitorCitation> citations) {
            this.citations.clear();
            if (citations != null) {
                this.citations.addAll(citations);
            }
            return this;
        }

        /**
         * <p>Structured data extracted from articles. Schema is dynamically generated per job. Field names are chosen semantically to match the content.</p>
         * <p>See <a href="https://www.newscatcherapi.com/docs/v3/catch-all/overview/dynamic-schemas">Understanding dynamic schemas</a> for integration guidance.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage enrichment(String key, Object value) {
            this.enrichment.put(key, value);
            return this;
        }

        /**
         * <p>Structured data extracted from articles. Schema is dynamically generated per job. Field names are chosen semantically to match the content.</p>
         * <p>See <a href="https://www.newscatcherapi.com/docs/v3/catch-all/overview/dynamic-schemas">Understanding dynamic schemas</a> for integration guidance.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllEnrichment(Map<String, Object> enrichment) {
            if (enrichment != null) {
                this.enrichment.putAll(enrichment);
            }
            return this;
        }

        /**
         * <p>Structured data extracted from articles. Schema is dynamically generated per job. Field names are chosen semantically to match the content.</p>
         * <p>See <a href="https://www.newscatcherapi.com/docs/v3/catch-all/overview/dynamic-schemas">Understanding dynamic schemas</a> for integration guidance.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "enrichment", nulls = Nulls.SKIP)
        public _FinalStage enrichment(Map<String, Object> enrichment) {
            this.enrichment.clear();
            if (enrichment != null) {
                this.enrichment.putAll(enrichment);
            }
            return this;
        }

        @java.lang.Override
        public MonitorRecord build() {
            return new MonitorRecord(
                    recordId, recordTitle, enrichment, citations, addedOn, updatedOn, additionalProperties);
        }
    }
}
