/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OwnershipFilter {
    public static final OwnershipFilter ALL = new OwnershipFilter(Value.ALL, "all");

    public static final OwnershipFilter OWN = new OwnershipFilter(Value.OWN, "own");

    public static final OwnershipFilter SHARED = new OwnershipFilter(Value.SHARED, "shared");

    private final Value value;

    private final String string;

    OwnershipFilter(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof OwnershipFilter && this.string.equals(((OwnershipFilter) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ALL:
                return visitor.visitAll();
            case OWN:
                return visitor.visitOwn();
            case SHARED:
                return visitor.visitShared();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OwnershipFilter valueOf(String value) {
        switch (value) {
            case "all":
                return ALL;
            case "own":
                return OWN;
            case "shared":
                return SHARED;
            default:
                return new OwnershipFilter(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ALL,

        OWN,

        SHARED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAll();

        T visitOwn();

        T visitShared();

        T visitUnknown(String unknownType);
    }
}
