/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PlanFeature.Builder.class)
public final class PlanFeature {
    private final String name;

    private final String code;

    private final Optional<String> valueType;

    private final Optional<Object> value;

    private final Optional<Double> currentUsage;

    private final Map<String, Object> additionalProperties;

    private PlanFeature(
            String name,
            String code,
            Optional<String> valueType,
            Optional<Object> value,
            Optional<Double> currentUsage,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.code = code;
        this.valueType = valueType;
        this.value = value;
        this.currentUsage = currentUsage;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Human-readable feature name.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Machine-readable feature identifier.
     */
    @JsonProperty("code")
    public String getCode() {
        return code;
    }

    /**
     * @return Data type of the feature value.
     */
    @JsonProperty("value_type")
    public Optional<String> getValueType() {
        return valueType;
    }

    /**
     * @return Feature limit. Type depends on <code>value_type</code>.
     */
    @JsonProperty("value")
    public Optional<Object> getValue() {
        return value;
    }

    /**
     * @return Current usage count for this feature.
     */
    @JsonProperty("current_usage")
    public Optional<Double> getCurrentUsage() {
        return currentUsage;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PlanFeature && equalTo((PlanFeature) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PlanFeature other) {
        return name.equals(other.name)
                && code.equals(other.code)
                && valueType.equals(other.valueType)
                && value.equals(other.value)
                && currentUsage.equals(other.currentUsage);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.code, this.valueType, this.value, this.currentUsage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Human-readable feature name.</p>
         */
        CodeStage name(@NotNull String name);

        Builder from(PlanFeature other);
    }

    public interface CodeStage {
        /**
         * <p>Machine-readable feature identifier.</p>
         */
        _FinalStage code(@NotNull String code);
    }

    public interface _FinalStage {
        PlanFeature build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Data type of the feature value.</p>
         */
        _FinalStage valueType(Optional<String> valueType);

        _FinalStage valueType(String valueType);

        /**
         * <p>Feature limit. Type depends on <code>value_type</code>.</p>
         */
        _FinalStage value(Optional<Object> value);

        _FinalStage value(Object value);

        /**
         * <p>Current usage count for this feature.</p>
         */
        _FinalStage currentUsage(Optional<Double> currentUsage);

        _FinalStage currentUsage(Double currentUsage);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, CodeStage, _FinalStage {
        private String name;

        private String code;

        private Optional<Double> currentUsage = Optional.empty();

        private Optional<Object> value = Optional.empty();

        private Optional<String> valueType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PlanFeature other) {
            name(other.getName());
            code(other.getCode());
            valueType(other.getValueType());
            value(other.getValue());
            currentUsage(other.getCurrentUsage());
            return this;
        }

        /**
         * <p>Human-readable feature name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public CodeStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Machine-readable feature identifier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("code")
        public _FinalStage code(@NotNull String code) {
            this.code = Objects.requireNonNull(code, "code must not be null");
            return this;
        }

        /**
         * <p>Current usage count for this feature.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage currentUsage(Double currentUsage) {
            this.currentUsage = Optional.ofNullable(currentUsage);
            return this;
        }

        /**
         * <p>Current usage count for this feature.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "current_usage", nulls = Nulls.SKIP)
        public _FinalStage currentUsage(Optional<Double> currentUsage) {
            this.currentUsage = currentUsage;
            return this;
        }

        /**
         * <p>Feature limit. Type depends on <code>value_type</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage value(Object value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        /**
         * <p>Feature limit. Type depends on <code>value_type</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public _FinalStage value(Optional<Object> value) {
            this.value = value;
            return this;
        }

        /**
         * <p>Data type of the feature value.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage valueType(String valueType) {
            this.valueType = Optional.ofNullable(valueType);
            return this;
        }

        /**
         * <p>Data type of the feature value.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "value_type", nulls = Nulls.SKIP)
        public _FinalStage valueType(Optional<String> valueType) {
            this.valueType = valueType;
            return this;
        }

        @java.lang.Override
        public PlanFeature build() {
            return new PlanFeature(name, code, valueType, value, currentUsage, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
