/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProjectOverviewResponseDto.Builder.class)
public final class ProjectOverviewResponseDto {
    private final String projectId;

    private final ProjectOverviewResponseDtoOverview overview;

    private final Map<String, Object> additionalProperties;

    private ProjectOverviewResponseDto(
            String projectId, ProjectOverviewResponseDtoOverview overview, Map<String, Object> additionalProperties) {
        this.projectId = projectId;
        this.overview = overview;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Project identifier.
     */
    @JsonProperty("project_id")
    public String getProjectId() {
        return projectId;
    }

    /**
     * @return Resource counts grouped by type.
     */
    @JsonProperty("overview")
    public ProjectOverviewResponseDtoOverview getOverview() {
        return overview;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProjectOverviewResponseDto && equalTo((ProjectOverviewResponseDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProjectOverviewResponseDto other) {
        return projectId.equals(other.projectId) && overview.equals(other.overview);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.projectId, this.overview);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ProjectIdStage builder() {
        return new Builder();
    }

    public interface ProjectIdStage {
        /**
         * <p>Project identifier.</p>
         */
        OverviewStage projectId(@NotNull String projectId);

        Builder from(ProjectOverviewResponseDto other);
    }

    public interface OverviewStage {
        /**
         * <p>Resource counts grouped by type.</p>
         */
        _FinalStage overview(@NotNull ProjectOverviewResponseDtoOverview overview);
    }

    public interface _FinalStage {
        ProjectOverviewResponseDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ProjectIdStage, OverviewStage, _FinalStage {
        private String projectId;

        private ProjectOverviewResponseDtoOverview overview;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ProjectOverviewResponseDto other) {
            projectId(other.getProjectId());
            overview(other.getOverview());
            return this;
        }

        /**
         * <p>Project identifier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("project_id")
        public OverviewStage projectId(@NotNull String projectId) {
            this.projectId = Objects.requireNonNull(projectId, "projectId must not be null");
            return this;
        }

        /**
         * <p>Resource counts grouped by type.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("overview")
        public _FinalStage overview(@NotNull ProjectOverviewResponseDtoOverview overview) {
            this.overview = Objects.requireNonNull(overview, "overview must not be null");
            return this;
        }

        @java.lang.Override
        public ProjectOverviewResponseDto build() {
            return new ProjectOverviewResponseDto(projectId, overview, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
