/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RemoveResourceResponseDto.Builder.class)
public final class RemoveResourceResponseDto {
    private final boolean success;

    private final String message;

    private final Map<String, Object> additionalProperties;

    private RemoveResourceResponseDto(boolean success, String message, Map<String, Object> additionalProperties) {
        this.success = success;
        this.message = message;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return True if the operation succeeded; false otherwise.
     */
    @JsonProperty("success")
    public boolean getSuccess() {
        return success;
    }

    /**
     * @return Human-readable result message.
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RemoveResourceResponseDto && equalTo((RemoveResourceResponseDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RemoveResourceResponseDto other) {
        return success == other.success && message.equals(other.message);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.success, this.message);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SuccessStage builder() {
        return new Builder();
    }

    public interface SuccessStage {
        /**
         * <p>True if the operation succeeded; false otherwise.</p>
         */
        MessageStage success(boolean success);

        Builder from(RemoveResourceResponseDto other);
    }

    public interface MessageStage {
        /**
         * <p>Human-readable result message.</p>
         */
        _FinalStage message(@NotNull String message);
    }

    public interface _FinalStage {
        RemoveResourceResponseDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SuccessStage, MessageStage, _FinalStage {
        private boolean success;

        private String message;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RemoveResourceResponseDto other) {
            success(other.getSuccess());
            message(other.getMessage());
            return this;
        }

        /**
         * <p>True if the operation succeeded; false otherwise.</p>
         * <p>True if the operation succeeded; false otherwise.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("success")
        public MessageStage success(boolean success) {
            this.success = success;
            return this;
        }

        /**
         * <p>Human-readable result message.</p>
         * <p>Human-readable result message.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public _FinalStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        @java.lang.Override
        public RemoveResourceResponseDto build() {
            return new RemoveResourceResponseDto(success, message, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
