/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Suggestion.Builder.class)
public final class Suggestion {
    private final IssueType issue;

    private final String message;

    private final Optional<String> example;

    private final Map<String, Object> additionalProperties;

    private Suggestion(
            IssueType issue, String message, Optional<String> example, Map<String, Object> additionalProperties) {
        this.issue = issue;
        this.message = message;
        this.example = example;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The issue this suggestion addresses.
     */
    @JsonProperty("issue")
    public IssueType getIssue() {
        return issue;
    }

    /**
     * @return Specific guidance for improving the query.
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    /**
     * @return Revised query demonstrating the suggested improvement.
     */
    @JsonProperty("example")
    public Optional<String> getExample() {
        return example;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Suggestion && equalTo((Suggestion) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Suggestion other) {
        return issue.equals(other.issue) && message.equals(other.message) && example.equals(other.example);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.issue, this.message, this.example);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IssueStage builder() {
        return new Builder();
    }

    public interface IssueStage {
        /**
         * <p>The issue this suggestion addresses.</p>
         */
        MessageStage issue(@NotNull IssueType issue);

        Builder from(Suggestion other);
    }

    public interface MessageStage {
        /**
         * <p>Specific guidance for improving the query.</p>
         */
        _FinalStage message(@NotNull String message);
    }

    public interface _FinalStage {
        Suggestion build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Revised query demonstrating the suggested improvement.</p>
         */
        _FinalStage example(Optional<String> example);

        _FinalStage example(String example);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IssueStage, MessageStage, _FinalStage {
        private IssueType issue;

        private String message;

        private Optional<String> example = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Suggestion other) {
            issue(other.getIssue());
            message(other.getMessage());
            example(other.getExample());
            return this;
        }

        /**
         * <p>The issue this suggestion addresses.</p>
         * <p>The issue this suggestion addresses.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("issue")
        public MessageStage issue(@NotNull IssueType issue) {
            this.issue = Objects.requireNonNull(issue, "issue must not be null");
            return this;
        }

        /**
         * <p>Specific guidance for improving the query.</p>
         * <p>Specific guidance for improving the query.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public _FinalStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        /**
         * <p>Revised query demonstrating the suggested improvement.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage example(String example) {
            this.example = Optional.ofNullable(example);
            return this;
        }

        /**
         * <p>Revised query demonstrating the suggested improvement.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "example", nulls = Nulls.SKIP)
        public _FinalStage example(Optional<String> example) {
            this.example = example;
            return this;
        }

        @java.lang.Override
        public Suggestion build() {
            return new Suggestion(issue, message, example, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
