/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TestWebhookResponseDto.Builder.class)
public final class TestWebhookResponseDto {
    private final boolean success;

    private final String message;

    private final Optional<Integer> httpStatusCode;

    private final Optional<Object> responseBody;

    private final Map<String, Object> additionalProperties;

    private TestWebhookResponseDto(
            boolean success,
            String message,
            Optional<Integer> httpStatusCode,
            Optional<Object> responseBody,
            Map<String, Object> additionalProperties) {
        this.success = success;
        this.message = message;
        this.httpStatusCode = httpStatusCode;
        this.responseBody = responseBody;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return True if the test delivery received a 2xx response; false otherwise.
     */
    @JsonProperty("success")
    public boolean getSuccess() {
        return success;
    }

    /**
     * @return Human-readable result message.
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    /**
     * @return HTTP status code returned by the webhook endpoint.
     */
    @JsonProperty("http_status_code")
    public Optional<Integer> getHttpStatusCode() {
        return httpStatusCode;
    }

    /**
     * @return Response body returned by the webhook endpoint. Type varies by target.
     */
    @JsonProperty("response_body")
    public Optional<Object> getResponseBody() {
        return responseBody;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TestWebhookResponseDto && equalTo((TestWebhookResponseDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TestWebhookResponseDto other) {
        return success == other.success
                && message.equals(other.message)
                && httpStatusCode.equals(other.httpStatusCode)
                && responseBody.equals(other.responseBody);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.success, this.message, this.httpStatusCode, this.responseBody);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SuccessStage builder() {
        return new Builder();
    }

    public interface SuccessStage {
        /**
         * <p>True if the test delivery received a 2xx response; false otherwise.</p>
         */
        MessageStage success(boolean success);

        Builder from(TestWebhookResponseDto other);
    }

    public interface MessageStage {
        /**
         * <p>Human-readable result message.</p>
         */
        _FinalStage message(@NotNull String message);
    }

    public interface _FinalStage {
        TestWebhookResponseDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>HTTP status code returned by the webhook endpoint.</p>
         */
        _FinalStage httpStatusCode(Optional<Integer> httpStatusCode);

        _FinalStage httpStatusCode(Integer httpStatusCode);

        /**
         * <p>Response body returned by the webhook endpoint. Type varies by target.</p>
         */
        _FinalStage responseBody(Optional<Object> responseBody);

        _FinalStage responseBody(Object responseBody);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SuccessStage, MessageStage, _FinalStage {
        private boolean success;

        private String message;

        private Optional<Object> responseBody = Optional.empty();

        private Optional<Integer> httpStatusCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TestWebhookResponseDto other) {
            success(other.getSuccess());
            message(other.getMessage());
            httpStatusCode(other.getHttpStatusCode());
            responseBody(other.getResponseBody());
            return this;
        }

        /**
         * <p>True if the test delivery received a 2xx response; false otherwise.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("success")
        public MessageStage success(boolean success) {
            this.success = success;
            return this;
        }

        /**
         * <p>Human-readable result message.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public _FinalStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        /**
         * <p>Response body returned by the webhook endpoint. Type varies by target.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage responseBody(Object responseBody) {
            this.responseBody = Optional.ofNullable(responseBody);
            return this;
        }

        /**
         * <p>Response body returned by the webhook endpoint. Type varies by target.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "response_body", nulls = Nulls.SKIP)
        public _FinalStage responseBody(Optional<Object> responseBody) {
            this.responseBody = responseBody;
            return this;
        }

        /**
         * <p>HTTP status code returned by the webhook endpoint.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage httpStatusCode(Integer httpStatusCode) {
            this.httpStatusCode = Optional.ofNullable(httpStatusCode);
            return this;
        }

        /**
         * <p>HTTP status code returned by the webhook endpoint.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "http_status_code", nulls = Nulls.SKIP)
        public _FinalStage httpStatusCode(Optional<Integer> httpStatusCode) {
            this.httpStatusCode = httpStatusCode;
            return this;
        }

        @java.lang.Override
        public TestWebhookResponseDto build() {
            return new TestWebhookResponseDto(success, message, httpStatusCode, responseBody, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
