/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ValidatorSchema.Builder.class)
public final class ValidatorSchema {
    private final String name;

    private final String description;

    private final Optional<String> type;

    private final Map<String, Object> additionalProperties;

    private ValidatorSchema(
            String name, String description, Optional<String> type, Map<String, Object> additionalProperties) {
        this.name = name;
        this.description = description;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Validator field name (snake_case recommended).
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return What this validator checks for in the article.
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    /**
     * @return Validator type (currently only boolean supported).
     */
    @JsonProperty("type")
    public Optional<String> getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ValidatorSchema && equalTo((ValidatorSchema) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ValidatorSchema other) {
        return name.equals(other.name) && description.equals(other.description) && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.description, this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Validator field name (snake_case recommended).</p>
         */
        DescriptionStage name(@NotNull String name);

        Builder from(ValidatorSchema other);
    }

    public interface DescriptionStage {
        /**
         * <p>What this validator checks for in the article.</p>
         */
        _FinalStage description(@NotNull String description);
    }

    public interface _FinalStage {
        ValidatorSchema build();

        /**
         * <p>Validator type (currently only boolean supported).</p>
         */
        _FinalStage type(Optional<String> type);

        _FinalStage type(String type);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, DescriptionStage, _FinalStage {
        private String name;

        private String description;

        private Optional<String> type = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ValidatorSchema other) {
            name(other.getName());
            description(other.getDescription());
            type(other.getType());
            return this;
        }

        /**
         * <p>Validator field name (snake_case recommended).</p>
         * <p>Validator field name (snake_case recommended).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public DescriptionStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>What this validator checks for in the article.</p>
         * <p>What this validator checks for in the article.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public _FinalStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        /**
         * <p>Validator type (currently only boolean supported).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(String type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>Validator type (currently only boolean supported).</p>
         */
        @java.lang.Override
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public _FinalStage type(Optional<String> type) {
            this.type = type;
            return this;
        }

        @java.lang.Override
        public ValidatorSchema build() {
            return new ValidatorSchema(name, description, type, additionalProperties);
        }
    }
}
