/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.jobs;

import com.newscatcher.catchall.core.ClientOptions;
import com.newscatcher.catchall.core.RequestOptions;
import com.newscatcher.catchall.resources.jobs.requests.GetJobResultsRequest;
import com.newscatcher.catchall.resources.jobs.requests.GetJobStatusRequest;
import com.newscatcher.catchall.resources.jobs.requests.SubmitRequestDto;
import com.newscatcher.catchall.types.ListUserJobsResponseDto;
import com.newscatcher.catchall.types.PullJobResponseDto;
import com.newscatcher.catchall.types.StatusResponseDto;
import com.newscatcher.catchall.types.SubmitResponseBody;
import java.util.List;

public class JobsClient {
    protected final ClientOptions clientOptions;

    private final RawJobsClient rawClient;

    public JobsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawJobsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawJobsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Submit a natural language query to create a new processing job.
     */
    public SubmitResponseBody createJob(SubmitRequestDto request) {
        return this.rawClient.createJob(request).body();
    }

    /**
     * Submit a natural language query to create a new processing job.
     */
    public SubmitResponseBody createJob(SubmitRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.createJob(request, requestOptions).body();
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public StatusResponseDto getJobStatus(String jobId) {
        return this.rawClient.getJobStatus(jobId).body();
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public StatusResponseDto getJobStatus(String jobId, GetJobStatusRequest request) {
        return this.rawClient.getJobStatus(jobId, request).body();
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public StatusResponseDto getJobStatus(String jobId, GetJobStatusRequest request, RequestOptions requestOptions) {
        return this.rawClient.getJobStatus(jobId, request, requestOptions).body();
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public List<ListUserJobsResponseDto> getUserJobs() {
        return this.rawClient.getUserJobs().body();
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public List<ListUserJobsResponseDto> getUserJobs(RequestOptions requestOptions) {
        return this.rawClient.getUserJobs(requestOptions).body();
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public PullJobResponseDto getJobResults(String jobId) {
        return this.rawClient.getJobResults(jobId).body();
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public PullJobResponseDto getJobResults(String jobId, GetJobResultsRequest request) {
        return this.rawClient.getJobResults(jobId, request).body();
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public PullJobResponseDto getJobResults(String jobId, GetJobResultsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getJobResults(jobId, request, requestOptions).body();
    }
}
