/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.jobs;

import com.newscatcher.catchall.core.ClientOptions;
import com.newscatcher.catchall.core.RequestOptions;
import com.newscatcher.catchall.resources.jobs.requests.ContinueRequestDto;
import com.newscatcher.catchall.resources.jobs.requests.DeleteJobRequest;
import com.newscatcher.catchall.resources.jobs.requests.GetJobResultsCsvRequest;
import com.newscatcher.catchall.resources.jobs.requests.GetJobResultsRequest;
import com.newscatcher.catchall.resources.jobs.requests.GetJobStatusRequest;
import com.newscatcher.catchall.resources.jobs.requests.GetUserJobsRequest;
import com.newscatcher.catchall.resources.jobs.requests.InitializeRequestDto;
import com.newscatcher.catchall.resources.jobs.requests.SubmitRequestDto;
import com.newscatcher.catchall.resources.jobs.requests.ValidateQueryRequestDto;
import com.newscatcher.catchall.types.ContinueResponseDto;
import com.newscatcher.catchall.types.DeleteJobResponseDto;
import com.newscatcher.catchall.types.InitializeResponseDto;
import com.newscatcher.catchall.types.ListUserJobsResponseDto;
import com.newscatcher.catchall.types.PullJobResponseDto;
import com.newscatcher.catchall.types.StatusResponseDto;
import com.newscatcher.catchall.types.SubmitResponseDto;
import com.newscatcher.catchall.types.ValidateQueryResponseDto;

public class JobsClient {
    protected final ClientOptions clientOptions;

    private final RawJobsClient rawClient;

    public JobsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawJobsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawJobsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public ListUserJobsResponseDto getUserJobs() {
        return this.rawClient.getUserJobs().body();
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public ListUserJobsResponseDto getUserJobs(RequestOptions requestOptions) {
        return this.rawClient.getUserJobs(requestOptions).body();
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public ListUserJobsResponseDto getUserJobs(GetUserJobsRequest request) {
        return this.rawClient.getUserJobs(request).body();
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public ListUserJobsResponseDto getUserJobs(GetUserJobsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getUserJobs(request, requestOptions).body();
    }

    /**
     * Checks whether a query is well-formed and likely to produce good results before submitting a job.
     * <p>Returns a quality assessment with a status level, identified issues, and actionable suggestions.</p>
     */
    public ValidateQueryResponseDto validateQuery(ValidateQueryRequestDto request) {
        return this.rawClient.validateQuery(request).body();
    }

    /**
     * Checks whether a query is well-formed and likely to produce good results before submitting a job.
     * <p>Returns a quality assessment with a status level, identified issues, and actionable suggestions.</p>
     */
    public ValidateQueryResponseDto validateQuery(ValidateQueryRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.validateQuery(request, requestOptions).body();
    }

    /**
     * Get suggested validators, enrichments, and date ranges for a query.
     */
    public InitializeResponseDto initialize(InitializeRequestDto request) {
        return this.rawClient.initialize(request).body();
    }

    /**
     * Get suggested validators, enrichments, and date ranges for a query.
     */
    public InitializeResponseDto initialize(InitializeRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.initialize(request, requestOptions).body();
    }

    /**
     * Submit a query to create a new processing job.
     */
    public SubmitResponseDto createJob(SubmitRequestDto request) {
        return this.rawClient.createJob(request).body();
    }

    /**
     * Submit a query to create a new processing job.
     */
    public SubmitResponseDto createJob(SubmitRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.createJob(request, requestOptions).body();
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public StatusResponseDto getJobStatus(String jobId) {
        return this.rawClient.getJobStatus(jobId).body();
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public StatusResponseDto getJobStatus(String jobId, RequestOptions requestOptions) {
        return this.rawClient.getJobStatus(jobId, requestOptions).body();
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public StatusResponseDto getJobStatus(String jobId, GetJobStatusRequest request) {
        return this.rawClient.getJobStatus(jobId, request).body();
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public StatusResponseDto getJobStatus(String jobId, GetJobStatusRequest request, RequestOptions requestOptions) {
        return this.rawClient.getJobStatus(jobId, request, requestOptions).body();
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public PullJobResponseDto getJobResults(String jobId) {
        return this.rawClient.getJobResults(jobId).body();
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public PullJobResponseDto getJobResults(String jobId, RequestOptions requestOptions) {
        return this.rawClient.getJobResults(jobId, requestOptions).body();
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public PullJobResponseDto getJobResults(String jobId, GetJobResultsRequest request) {
        return this.rawClient.getJobResults(jobId, request).body();
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public PullJobResponseDto getJobResults(String jobId, GetJobResultsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getJobResults(jobId, request, requestOptions).body();
    }

    /**
     * Returns a completed job's result records as a CSV download. One row per record, with enrichment fields as columns, citations as a JSON column, and connected entities split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns.
     */
    public String getJobResultsCsv(String jobId) {
        return this.rawClient.getJobResultsCsv(jobId).body();
    }

    /**
     * Returns a completed job's result records as a CSV download. One row per record, with enrichment fields as columns, citations as a JSON column, and connected entities split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns.
     */
    public String getJobResultsCsv(String jobId, RequestOptions requestOptions) {
        return this.rawClient.getJobResultsCsv(jobId, requestOptions).body();
    }

    /**
     * Returns a completed job's result records as a CSV download. One row per record, with enrichment fields as columns, citations as a JSON column, and connected entities split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns.
     */
    public String getJobResultsCsv(String jobId, GetJobResultsCsvRequest request) {
        return this.rawClient.getJobResultsCsv(jobId, request).body();
    }

    /**
     * Returns a completed job's result records as a CSV download. One row per record, with enrichment fields as columns, citations as a JSON column, and connected entities split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns.
     */
    public String getJobResultsCsv(String jobId, GetJobResultsCsvRequest request, RequestOptions requestOptions) {
        return this.rawClient.getJobResultsCsv(jobId, request, requestOptions).body();
    }

    /**
     * Continue an existing job to process more records beyond the initial limit.
     */
    public ContinueResponseDto continueJob(ContinueRequestDto request) {
        return this.rawClient.continueJob(request).body();
    }

    /**
     * Continue an existing job to process more records beyond the initial limit.
     */
    public ContinueResponseDto continueJob(ContinueRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.continueJob(request, requestOptions).body();
    }

    /**
     * Soft-deletes a job. The job is flagged as deleted and no longer appears in list results. The underlying data is retained.
     * <p>Only the job owner can delete a job. Returns <code>404</code> if the job is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted job returns <code>200</code>.</p>
     */
    public DeleteJobResponseDto deleteJob(String jobId) {
        return this.rawClient.deleteJob(jobId).body();
    }

    /**
     * Soft-deletes a job. The job is flagged as deleted and no longer appears in list results. The underlying data is retained.
     * <p>Only the job owner can delete a job. Returns <code>404</code> if the job is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted job returns <code>200</code>.</p>
     */
    public DeleteJobResponseDto deleteJob(String jobId, RequestOptions requestOptions) {
        return this.rawClient.deleteJob(jobId, requestOptions).body();
    }

    /**
     * Soft-deletes a job. The job is flagged as deleted and no longer appears in list results. The underlying data is retained.
     * <p>Only the job owner can delete a job. Returns <code>404</code> if the job is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted job returns <code>200</code>.</p>
     */
    public DeleteJobResponseDto deleteJob(String jobId, DeleteJobRequest request) {
        return this.rawClient.deleteJob(jobId, request).body();
    }

    /**
     * Soft-deletes a job. The job is flagged as deleted and no longer appears in list results. The underlying data is retained.
     * <p>Only the job owner can delete a job. Returns <code>404</code> if the job is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted job returns <code>200</code>.</p>
     */
    public DeleteJobResponseDto deleteJob(String jobId, DeleteJobRequest request, RequestOptions requestOptions) {
        return this.rawClient.deleteJob(jobId, request, requestOptions).body();
    }
}
