/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.jobs;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.newscatcher.catchall.core.CatchAllApiApiException;
import com.newscatcher.catchall.core.CatchAllApiException;
import com.newscatcher.catchall.core.CatchAllApiHttpResponse;
import com.newscatcher.catchall.core.ClientOptions;
import com.newscatcher.catchall.core.MediaTypes;
import com.newscatcher.catchall.core.ObjectMappers;
import com.newscatcher.catchall.core.QueryStringMapper;
import com.newscatcher.catchall.core.RequestOptions;
import com.newscatcher.catchall.errors.BadRequestError;
import com.newscatcher.catchall.errors.ForbiddenError;
import com.newscatcher.catchall.errors.NotFoundError;
import com.newscatcher.catchall.errors.UnprocessableEntityError;
import com.newscatcher.catchall.resources.jobs.requests.ContinueRequestDto;
import com.newscatcher.catchall.resources.jobs.requests.GetJobResultsRequest;
import com.newscatcher.catchall.resources.jobs.requests.GetJobStatusRequest;
import com.newscatcher.catchall.resources.jobs.requests.GetUserJobsRequest;
import com.newscatcher.catchall.resources.jobs.requests.InitializeRequestDto;
import com.newscatcher.catchall.resources.jobs.requests.SubmitRequestDto;
import com.newscatcher.catchall.types.ContinueResponseDto;
import com.newscatcher.catchall.types.Error;
import com.newscatcher.catchall.types.InitializeResponseDto;
import com.newscatcher.catchall.types.ListUserJobsResponseDto;
import com.newscatcher.catchall.types.PullJobResponseDto;
import com.newscatcher.catchall.types.StatusResponseDto;
import com.newscatcher.catchall.types.SubmitResponseBody;
import com.newscatcher.catchall.types.ValidationErrorResponse;
import java.io.IOException;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawJobsClient {
    protected final ClientOptions clientOptions;

    public RawJobsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get suggested validators, enrichments, and date ranges for a query before submitting a job.
     * <p>Returns LLM-generated suggestions based on query analysis and validates against plan limits.</p>
     */
    public CatchAllApiHttpResponse<InitializeResponseDto> initialize(InitializeRequestDto request) {
        return initialize(request, null);
    }

    /**
     * Get suggested validators, enrichments, and date ranges for a query before submitting a job.
     * <p>Returns LLM-generated suggestions based on query analysis and validates against plan limits.</p>
     */
    public CatchAllApiHttpResponse<InitializeResponseDto> initialize(
            InitializeRequestDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/initialize");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, InitializeResponseDto.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ValidationErrorResponse.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Submit a natural language query to create a new processing job.
     * <p>Optionally specify context, date ranges, limit, custom validators, and enrichments.
     * If dates exceed plan limits, returns 400 error.</p>
     */
    public CatchAllApiHttpResponse<SubmitResponseBody> createJob(SubmitRequestDto request) {
        return createJob(request, null);
    }

    /**
     * Submit a natural language query to create a new processing job.
     * <p>Optionally specify context, date ranges, limit, custom validators, and enrichments.
     * If dates exceed plan limits, returns 400 error.</p>
     */
    public CatchAllApiHttpResponse<SubmitResponseBody> createJob(
            SubmitRequestDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/submit");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SubmitResponseBody.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ValidationErrorResponse.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Continue an existing job to process more records beyond the initial limit.
     */
    public CatchAllApiHttpResponse<ContinueResponseDto> continueJob(ContinueRequestDto request) {
        return continueJob(request, null);
    }

    /**
     * Continue an existing job to process more records beyond the initial limit.
     */
    public CatchAllApiHttpResponse<ContinueResponseDto> continueJob(
            ContinueRequestDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/continue");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ContinueResponseDto.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ValidationErrorResponse.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public CatchAllApiHttpResponse<StatusResponseDto> getJobStatus(String jobId) {
        return getJobStatus(jobId, GetJobStatusRequest.builder().build());
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public CatchAllApiHttpResponse<StatusResponseDto> getJobStatus(String jobId, RequestOptions requestOptions) {
        return getJobStatus(jobId, GetJobStatusRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public CatchAllApiHttpResponse<StatusResponseDto> getJobStatus(String jobId, GetJobStatusRequest request) {
        return getJobStatus(jobId, request, null);
    }

    /**
     * Retrieve the current processing status of a job.
     */
    public CatchAllApiHttpResponse<StatusResponseDto> getJobStatus(
            String jobId, GetJobStatusRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/status")
                .addPathSegment(jobId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, StatusResponseDto.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public CatchAllApiHttpResponse<List<ListUserJobsResponseDto>> getUserJobs() {
        return getUserJobs(GetUserJobsRequest.builder().build());
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public CatchAllApiHttpResponse<List<ListUserJobsResponseDto>> getUserJobs(RequestOptions requestOptions) {
        return getUserJobs(GetUserJobsRequest.builder().build(), requestOptions);
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public CatchAllApiHttpResponse<List<ListUserJobsResponseDto>> getUserJobs(GetUserJobsRequest request) {
        return getUserJobs(request, null);
    }

    /**
     * Returns all jobs created by the authenticated user.
     */
    public CatchAllApiHttpResponse<List<ListUserJobsResponseDto>> getUserJobs(
            GetUserJobsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/jobs/user");
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPageSize().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page_size", request.getPageSize().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, new TypeReference<List<ListUserJobsResponseDto>>() {}),
                        response);
            }
            try {
                if (response.code() == 403) {
                    throw new ForbiddenError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public CatchAllApiHttpResponse<PullJobResponseDto> getJobResults(String jobId) {
        return getJobResults(jobId, GetJobResultsRequest.builder().build());
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public CatchAllApiHttpResponse<PullJobResponseDto> getJobResults(String jobId, RequestOptions requestOptions) {
        return getJobResults(jobId, GetJobResultsRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public CatchAllApiHttpResponse<PullJobResponseDto> getJobResults(String jobId, GetJobResultsRequest request) {
        return getJobResults(jobId, request, null);
    }

    /**
     * Retrieve the final results for a completed job.
     */
    public CatchAllApiHttpResponse<PullJobResponseDto> getJobResults(
            String jobId, GetJobResultsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/pull")
                .addPathSegment(jobId);
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPageSize().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page_size", request.getPageSize().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PullJobResponseDto.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }
}
