/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.monitors;

import com.newscatcher.catchall.core.ClientOptions;
import com.newscatcher.catchall.core.RequestOptions;
import com.newscatcher.catchall.resources.monitors.requests.CreateMonitorRequestDto;
import com.newscatcher.catchall.resources.monitors.requests.DeleteMonitorRequest;
import com.newscatcher.catchall.resources.monitors.requests.DisableMonitorRequest;
import com.newscatcher.catchall.resources.monitors.requests.EnableMonitorRequestDto;
import com.newscatcher.catchall.resources.monitors.requests.GetMonitorStatusHistoryRequest;
import com.newscatcher.catchall.resources.monitors.requests.ListMonitorJobsRequest;
import com.newscatcher.catchall.resources.monitors.requests.ListMonitorsRequest;
import com.newscatcher.catchall.resources.monitors.requests.PullMonitorResultsRequest;
import com.newscatcher.catchall.resources.monitors.requests.UpdateMonitorRequestDto;
import com.newscatcher.catchall.resources.monitors.types.DisableMonitorResponse;
import com.newscatcher.catchall.resources.monitors.types.EnableMonitorResponse;
import com.newscatcher.catchall.resources.monitors.types.ListMonitorJobsResponse;
import com.newscatcher.catchall.types.CreateMonitorResponseDto;
import com.newscatcher.catchall.types.DeleteMonitorResponseDto;
import com.newscatcher.catchall.types.ListMonitorsResponseDto;
import com.newscatcher.catchall.types.MonitorStatusHistoryResponseDto;
import com.newscatcher.catchall.types.PullMonitorResponseDto;
import com.newscatcher.catchall.types.UpdateMonitorResponseDto;
import java.util.concurrent.CompletableFuture;

public class AsyncMonitorsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawMonitorsClient rawClient;

    public AsyncMonitorsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawMonitorsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawMonitorsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns all monitors created by the authenticated user.
     */
    public CompletableFuture<ListMonitorsResponseDto> listMonitors() {
        return this.rawClient.listMonitors().thenApply(response -> response.body());
    }

    /**
     * Returns all monitors created by the authenticated user.
     */
    public CompletableFuture<ListMonitorsResponseDto> listMonitors(RequestOptions requestOptions) {
        return this.rawClient.listMonitors(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns all monitors created by the authenticated user.
     */
    public CompletableFuture<ListMonitorsResponseDto> listMonitors(ListMonitorsRequest request) {
        return this.rawClient.listMonitors(request).thenApply(response -> response.body());
    }

    /**
     * Returns all monitors created by the authenticated user.
     */
    public CompletableFuture<ListMonitorsResponseDto> listMonitors(
            ListMonitorsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listMonitors(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create a scheduled monitor based on a reference job.
     */
    public CompletableFuture<CreateMonitorResponseDto> createMonitor(CreateMonitorRequestDto request) {
        return this.rawClient.createMonitor(request).thenApply(response -> response.body());
    }

    /**
     * Create a scheduled monitor based on a reference job.
     */
    public CompletableFuture<CreateMonitorResponseDto> createMonitor(
            CreateMonitorRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.createMonitor(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve aggregated results from all jobs executed by a monitor.
     */
    public CompletableFuture<PullMonitorResponseDto> pullMonitorResults(String monitorId) {
        return this.rawClient.pullMonitorResults(monitorId).thenApply(response -> response.body());
    }

    /**
     * Retrieve aggregated results from all jobs executed by a monitor.
     */
    public CompletableFuture<PullMonitorResponseDto> pullMonitorResults(
            String monitorId, RequestOptions requestOptions) {
        return this.rawClient.pullMonitorResults(monitorId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve aggregated results from all jobs executed by a monitor.
     */
    public CompletableFuture<PullMonitorResponseDto> pullMonitorResults(
            String monitorId, PullMonitorResultsRequest request) {
        return this.rawClient.pullMonitorResults(monitorId, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve aggregated results from all jobs executed by a monitor.
     */
    public CompletableFuture<PullMonitorResponseDto> pullMonitorResults(
            String monitorId, PullMonitorResultsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .pullMonitorResults(monitorId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Return all jobs executed by a monitor.
     */
    public CompletableFuture<ListMonitorJobsResponse> listMonitorJobs(String monitorId) {
        return this.rawClient.listMonitorJobs(monitorId).thenApply(response -> response.body());
    }

    /**
     * Return all jobs executed by a monitor.
     */
    public CompletableFuture<ListMonitorJobsResponse> listMonitorJobs(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.listMonitorJobs(monitorId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Return all jobs executed by a monitor.
     */
    public CompletableFuture<ListMonitorJobsResponse> listMonitorJobs(
            String monitorId, ListMonitorJobsRequest request) {
        return this.rawClient.listMonitorJobs(monitorId, request).thenApply(response -> response.body());
    }

    /**
     * Return all jobs executed by a monitor.
     */
    public CompletableFuture<ListMonitorJobsResponse> listMonitorJobs(
            String monitorId, ListMonitorJobsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .listMonitorJobs(monitorId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Returns the full execution history of a monitor as a list of status entries, ordered from newest to oldest.
     */
    public CompletableFuture<MonitorStatusHistoryResponseDto> getMonitorStatusHistory(String monitorId) {
        return this.rawClient.getMonitorStatusHistory(monitorId).thenApply(response -> response.body());
    }

    /**
     * Returns the full execution history of a monitor as a list of status entries, ordered from newest to oldest.
     */
    public CompletableFuture<MonitorStatusHistoryResponseDto> getMonitorStatusHistory(
            String monitorId, RequestOptions requestOptions) {
        return this.rawClient.getMonitorStatusHistory(monitorId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns the full execution history of a monitor as a list of status entries, ordered from newest to oldest.
     */
    public CompletableFuture<MonitorStatusHistoryResponseDto> getMonitorStatusHistory(
            String monitorId, GetMonitorStatusHistoryRequest request) {
        return this.rawClient.getMonitorStatusHistory(monitorId, request).thenApply(response -> response.body());
    }

    /**
     * Returns the full execution history of a monitor as a list of status entries, ordered from newest to oldest.
     */
    public CompletableFuture<MonitorStatusHistoryResponseDto> getMonitorStatusHistory(
            String monitorId, GetMonitorStatusHistoryRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getMonitorStatusHistory(monitorId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Resume scheduled job execution for a monitor.
     */
    public CompletableFuture<EnableMonitorResponse> enableMonitor(String monitorId) {
        return this.rawClient.enableMonitor(monitorId).thenApply(response -> response.body());
    }

    /**
     * Resume scheduled job execution for a monitor.
     */
    public CompletableFuture<EnableMonitorResponse> enableMonitor(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.enableMonitor(monitorId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Resume scheduled job execution for a monitor.
     */
    public CompletableFuture<EnableMonitorResponse> enableMonitor(String monitorId, EnableMonitorRequestDto request) {
        return this.rawClient.enableMonitor(monitorId, request).thenApply(response -> response.body());
    }

    /**
     * Resume scheduled job execution for a monitor.
     */
    public CompletableFuture<EnableMonitorResponse> enableMonitor(
            String monitorId, EnableMonitorRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.enableMonitor(monitorId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Stop scheduled job execution for a monitor.
     */
    public CompletableFuture<DisableMonitorResponse> disableMonitor(String monitorId) {
        return this.rawClient.disableMonitor(monitorId).thenApply(response -> response.body());
    }

    /**
     * Stop scheduled job execution for a monitor.
     */
    public CompletableFuture<DisableMonitorResponse> disableMonitor(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.disableMonitor(monitorId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Stop scheduled job execution for a monitor.
     */
    public CompletableFuture<DisableMonitorResponse> disableMonitor(String monitorId, DisableMonitorRequest request) {
        return this.rawClient.disableMonitor(monitorId, request).thenApply(response -> response.body());
    }

    /**
     * Stop scheduled job execution for a monitor.
     */
    public CompletableFuture<DisableMonitorResponse> disableMonitor(
            String monitorId, DisableMonitorRequest request, RequestOptions requestOptions) {
        return this.rawClient.disableMonitor(monitorId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Soft-deletes a monitor. The monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the monitor owner can delete a monitor. Returns <code>404</code> if the
     * monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted monitor returns <code>200</code>.</p>
     */
    public CompletableFuture<DeleteMonitorResponseDto> deleteMonitor(String monitorId) {
        return this.rawClient.deleteMonitor(monitorId).thenApply(response -> response.body());
    }

    /**
     * Soft-deletes a monitor. The monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the monitor owner can delete a monitor. Returns <code>404</code> if the
     * monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted monitor returns <code>200</code>.</p>
     */
    public CompletableFuture<DeleteMonitorResponseDto> deleteMonitor(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.deleteMonitor(monitorId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Soft-deletes a monitor. The monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the monitor owner can delete a monitor. Returns <code>404</code> if the
     * monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted monitor returns <code>200</code>.</p>
     */
    public CompletableFuture<DeleteMonitorResponseDto> deleteMonitor(String monitorId, DeleteMonitorRequest request) {
        return this.rawClient.deleteMonitor(monitorId, request).thenApply(response -> response.body());
    }

    /**
     * Soft-deletes a monitor. The monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the monitor owner can delete a monitor. Returns <code>404</code> if the
     * monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted monitor returns <code>200</code>.</p>
     */
    public CompletableFuture<DeleteMonitorResponseDto> deleteMonitor(
            String monitorId, DeleteMonitorRequest request, RequestOptions requestOptions) {
        return this.rawClient.deleteMonitor(monitorId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Update the webhook configuration for an existing monitor.
     */
    public CompletableFuture<UpdateMonitorResponseDto> updateMonitor(String monitorId) {
        return this.rawClient.updateMonitor(monitorId).thenApply(response -> response.body());
    }

    /**
     * Update the webhook configuration for an existing monitor.
     */
    public CompletableFuture<UpdateMonitorResponseDto> updateMonitor(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.updateMonitor(monitorId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Update the webhook configuration for an existing monitor.
     */
    public CompletableFuture<UpdateMonitorResponseDto> updateMonitor(
            String monitorId, UpdateMonitorRequestDto request) {
        return this.rawClient.updateMonitor(monitorId, request).thenApply(response -> response.body());
    }

    /**
     * Update the webhook configuration for an existing monitor.
     */
    public CompletableFuture<UpdateMonitorResponseDto> updateMonitor(
            String monitorId, UpdateMonitorRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.updateMonitor(monitorId, request, requestOptions).thenApply(response -> response.body());
    }
}
