/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.eventmonitors;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.newscatcher.catchall.core.CatchAllApiApiException;
import com.newscatcher.catchall.core.CatchAllApiException;
import com.newscatcher.catchall.core.CatchAllApiHttpResponse;
import com.newscatcher.catchall.core.ClientOptions;
import com.newscatcher.catchall.core.MediaTypes;
import com.newscatcher.catchall.core.ObjectMappers;
import com.newscatcher.catchall.core.QueryStringMapper;
import com.newscatcher.catchall.core.RequestOptions;
import com.newscatcher.catchall.core.RetryInterceptor;
import com.newscatcher.catchall.errors.ForbiddenError;
import com.newscatcher.catchall.errors.NotFoundError;
import com.newscatcher.catchall.errors.UnauthorizedError;
import com.newscatcher.catchall.errors.UnprocessableEntityError;
import com.newscatcher.catchall.resources.eventmonitors.requests.CreateMonitorRequestDto;
import com.newscatcher.catchall.resources.eventmonitors.requests.DeleteMonitorRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.DisableMonitorRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.EnableMonitorRequestDto;
import com.newscatcher.catchall.resources.eventmonitors.requests.GetMonitorStatusHistoryRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.ListMonitorJobsRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.ListMonitorsRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.PullMonitorResultsCsvRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.PullMonitorResultsRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.UpdateMonitorRequestDto;
import com.newscatcher.catchall.resources.eventmonitors.types.DisableMonitorResponse;
import com.newscatcher.catchall.resources.eventmonitors.types.EnableMonitorResponse;
import com.newscatcher.catchall.resources.eventmonitors.types.ListMonitorJobsResponse;
import com.newscatcher.catchall.types.CreateMonitorResponseDto;
import com.newscatcher.catchall.types.DeleteMonitorResponseDto;
import com.newscatcher.catchall.types.Error;
import com.newscatcher.catchall.types.ListMonitorsResponseDto;
import com.newscatcher.catchall.types.MonitorStatusHistoryResponseDto;
import com.newscatcher.catchall.types.PullMonitorResponseDto;
import com.newscatcher.catchall.types.UpdateMonitorResponseDto;
import com.newscatcher.catchall.types.ValidationErrorResponse;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawEventMonitorsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawEventMonitorsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns all event monitors created by the authenticated user.
     */
    public CompletableFuture<CatchAllApiHttpResponse<ListMonitorsResponseDto>> listMonitors() {
        return listMonitors(ListMonitorsRequest.builder().build());
    }

    /**
     * Returns all event monitors created by the authenticated user.
     */
    public CompletableFuture<CatchAllApiHttpResponse<ListMonitorsResponseDto>> listMonitors(
            RequestOptions requestOptions) {
        return listMonitors(ListMonitorsRequest.builder().build(), requestOptions);
    }

    /**
     * Returns all event monitors created by the authenticated user.
     */
    public CompletableFuture<CatchAllApiHttpResponse<ListMonitorsResponseDto>> listMonitors(
            ListMonitorsRequest request) {
        return listMonitors(request, null);
    }

    /**
     * Returns all event monitors created by the authenticated user.
     */
    public CompletableFuture<CatchAllApiHttpResponse<ListMonitorsResponseDto>> listMonitors(
            ListMonitorsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors");
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPageSize().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page_size", request.getPageSize().get(), false);
        }
        if (request.getSearch().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "search", request.getSearch().get(), false);
        }
        if (request.getOwnership().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "ownership", request.getOwnership().get(), false);
        }
        if (request.getProjectId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "project_id", request.getProjectId().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<ListMonitorsResponseDto>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListMonitorsResponseDto.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ValidationErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Create a scheduled event monitor based on a reference job.
     */
    public CompletableFuture<CatchAllApiHttpResponse<CreateMonitorResponseDto>> createMonitor(
            CreateMonitorRequestDto request) {
        return createMonitor(request, null);
    }

    /**
     * Create a scheduled event monitor based on a reference job.
     */
    public CompletableFuture<CatchAllApiHttpResponse<CreateMonitorResponseDto>> createMonitor(
            CreateMonitorRequestDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors/create");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<CreateMonitorResponseDto>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateMonitorResponseDto.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ValidationErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Retrieve aggregated results from all jobs executed by an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<PullMonitorResponseDto>> pullMonitorResults(String monitorId) {
        return pullMonitorResults(monitorId, PullMonitorResultsRequest.builder().build());
    }

    /**
     * Retrieve aggregated results from all jobs executed by an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<PullMonitorResponseDto>> pullMonitorResults(
            String monitorId, RequestOptions requestOptions) {
        return pullMonitorResults(monitorId, PullMonitorResultsRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve aggregated results from all jobs executed by an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<PullMonitorResponseDto>> pullMonitorResults(
            String monitorId, PullMonitorResultsRequest request) {
        return pullMonitorResults(monitorId, request, null);
    }

    /**
     * Retrieve aggregated results from all jobs executed by an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<PullMonitorResponseDto>> pullMonitorResults(
            String monitorId, PullMonitorResultsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors/pull")
                .addPathSegment(monitorId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<PullMonitorResponseDto>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PullMonitorResponseDto.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ValidationErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Returns the most recent run's records as a CSV download. One row per record, with enrichment fields as columns and citations as a JSON column.
     * <p>If the event monitor's reference job used connected entity datasets, connected entities are split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns. When no entity dataset was used, those two columns are omitted from the export entirely.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<String>> pullMonitorResultsCsv(String monitorId) {
        return pullMonitorResultsCsv(
                monitorId, PullMonitorResultsCsvRequest.builder().build());
    }

    /**
     * Returns the most recent run's records as a CSV download. One row per record, with enrichment fields as columns and citations as a JSON column.
     * <p>If the event monitor's reference job used connected entity datasets, connected entities are split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns. When no entity dataset was used, those two columns are omitted from the export entirely.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<String>> pullMonitorResultsCsv(
            String monitorId, RequestOptions requestOptions) {
        return pullMonitorResultsCsv(
                monitorId, PullMonitorResultsCsvRequest.builder().build(), requestOptions);
    }

    /**
     * Returns the most recent run's records as a CSV download. One row per record, with enrichment fields as columns and citations as a JSON column.
     * <p>If the event monitor's reference job used connected entity datasets, connected entities are split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns. When no entity dataset was used, those two columns are omitted from the export entirely.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<String>> pullMonitorResultsCsv(
            String monitorId, PullMonitorResultsCsvRequest request) {
        return pullMonitorResultsCsv(monitorId, request, null);
    }

    /**
     * Returns the most recent run's records as a CSV download. One row per record, with enrichment fields as columns and citations as a JSON column.
     * <p>If the event monitor's reference job used connected entity datasets, connected entities are split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns. When no entity dataset was used, those two columns are omitted from the export entirely.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<String>> pullMonitorResultsCsv(
            String monitorId, PullMonitorResultsCsvRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors/pull")
                .addPathSegment(monitorId)
                .addPathSegments("csv");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<String>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(responseBodyString, response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Return all jobs executed by an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<ListMonitorJobsResponse>> listMonitorJobs(String monitorId) {
        return listMonitorJobs(monitorId, ListMonitorJobsRequest.builder().build());
    }

    /**
     * Return all jobs executed by an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<ListMonitorJobsResponse>> listMonitorJobs(
            String monitorId, RequestOptions requestOptions) {
        return listMonitorJobs(monitorId, ListMonitorJobsRequest.builder().build(), requestOptions);
    }

    /**
     * Return all jobs executed by an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<ListMonitorJobsResponse>> listMonitorJobs(
            String monitorId, ListMonitorJobsRequest request) {
        return listMonitorJobs(monitorId, request, null);
    }

    /**
     * Return all jobs executed by an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<ListMonitorJobsResponse>> listMonitorJobs(
            String monitorId, ListMonitorJobsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors")
                .addPathSegment(monitorId)
                .addPathSegments("jobs");
        if (request.getSort().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort", request.getSort().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<ListMonitorJobsResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListMonitorJobsResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ValidationErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Returns the full execution history of an event monitor as a list of status entries, ordered from newest to oldest.
     */
    public CompletableFuture<CatchAllApiHttpResponse<MonitorStatusHistoryResponseDto>> getMonitorStatusHistory(
            String monitorId) {
        return getMonitorStatusHistory(
                monitorId, GetMonitorStatusHistoryRequest.builder().build());
    }

    /**
     * Returns the full execution history of an event monitor as a list of status entries, ordered from newest to oldest.
     */
    public CompletableFuture<CatchAllApiHttpResponse<MonitorStatusHistoryResponseDto>> getMonitorStatusHistory(
            String monitorId, RequestOptions requestOptions) {
        return getMonitorStatusHistory(
                monitorId, GetMonitorStatusHistoryRequest.builder().build(), requestOptions);
    }

    /**
     * Returns the full execution history of an event monitor as a list of status entries, ordered from newest to oldest.
     */
    public CompletableFuture<CatchAllApiHttpResponse<MonitorStatusHistoryResponseDto>> getMonitorStatusHistory(
            String monitorId, GetMonitorStatusHistoryRequest request) {
        return getMonitorStatusHistory(monitorId, request, null);
    }

    /**
     * Returns the full execution history of an event monitor as a list of status entries, ordered from newest to oldest.
     */
    public CompletableFuture<CatchAllApiHttpResponse<MonitorStatusHistoryResponseDto>> getMonitorStatusHistory(
            String monitorId, GetMonitorStatusHistoryRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors")
                .addPathSegment(monitorId)
                .addPathSegments("status");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<MonitorStatusHistoryResponseDto>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, MonitorStatusHistoryResponseDto.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Resume scheduled job execution for an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<EnableMonitorResponse>> enableMonitor(String monitorId) {
        return enableMonitor(monitorId, EnableMonitorRequestDto.builder().build());
    }

    /**
     * Resume scheduled job execution for an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<EnableMonitorResponse>> enableMonitor(
            String monitorId, RequestOptions requestOptions) {
        return enableMonitor(monitorId, EnableMonitorRequestDto.builder().build(), requestOptions);
    }

    /**
     * Resume scheduled job execution for an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<EnableMonitorResponse>> enableMonitor(
            String monitorId, EnableMonitorRequestDto request) {
        return enableMonitor(monitorId, request, null);
    }

    /**
     * Resume scheduled job execution for an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<EnableMonitorResponse>> enableMonitor(
            String monitorId, EnableMonitorRequestDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors")
                .addPathSegment(monitorId)
                .addPathSegments("enable");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<EnableMonitorResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, EnableMonitorResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ValidationErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Stop scheduled job execution for an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<DisableMonitorResponse>> disableMonitor(String monitorId) {
        return disableMonitor(monitorId, DisableMonitorRequest.builder().build());
    }

    /**
     * Stop scheduled job execution for an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<DisableMonitorResponse>> disableMonitor(
            String monitorId, RequestOptions requestOptions) {
        return disableMonitor(monitorId, DisableMonitorRequest.builder().build(), requestOptions);
    }

    /**
     * Stop scheduled job execution for an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<DisableMonitorResponse>> disableMonitor(
            String monitorId, DisableMonitorRequest request) {
        return disableMonitor(monitorId, request, null);
    }

    /**
     * Stop scheduled job execution for an event monitor.
     */
    public CompletableFuture<CatchAllApiHttpResponse<DisableMonitorResponse>> disableMonitor(
            String monitorId, DisableMonitorRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors")
                .addPathSegment(monitorId)
                .addPathSegments("disable");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<DisableMonitorResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, DisableMonitorResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ValidationErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Soft-deletes an event monitor. The event monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the event monitor owner can delete an event monitor. Returns <code>404</code> if the
     * event monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted event monitor returns <code>200</code>.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<DeleteMonitorResponseDto>> deleteMonitor(String monitorId) {
        return deleteMonitor(monitorId, DeleteMonitorRequest.builder().build());
    }

    /**
     * Soft-deletes an event monitor. The event monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the event monitor owner can delete an event monitor. Returns <code>404</code> if the
     * event monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted event monitor returns <code>200</code>.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<DeleteMonitorResponseDto>> deleteMonitor(
            String monitorId, RequestOptions requestOptions) {
        return deleteMonitor(monitorId, DeleteMonitorRequest.builder().build(), requestOptions);
    }

    /**
     * Soft-deletes an event monitor. The event monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the event monitor owner can delete an event monitor. Returns <code>404</code> if the
     * event monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted event monitor returns <code>200</code>.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<DeleteMonitorResponseDto>> deleteMonitor(
            String monitorId, DeleteMonitorRequest request) {
        return deleteMonitor(monitorId, request, null);
    }

    /**
     * Soft-deletes an event monitor. The event monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the event monitor owner can delete an event monitor. Returns <code>404</code> if the
     * event monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted event monitor returns <code>200</code>.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<DeleteMonitorResponseDto>> deleteMonitor(
            String monitorId, DeleteMonitorRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors")
                .addPathSegment(monitorId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<DeleteMonitorResponseDto>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, DeleteMonitorResponseDto.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Update the webhook assignments, record limit, or schedule of an existing
     * event monitor. Omitted fields are left unchanged.
     * <p>Passing <code>schedule</code> replaces the event monitor's current schedule. The new
     * schedule takes effect from the next scheduler reload, and the old schedule
     * stops firing. The reference job cannot be changed.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<UpdateMonitorResponseDto>> updateMonitor(String monitorId) {
        return updateMonitor(monitorId, UpdateMonitorRequestDto.builder().build());
    }

    /**
     * Update the webhook assignments, record limit, or schedule of an existing
     * event monitor. Omitted fields are left unchanged.
     * <p>Passing <code>schedule</code> replaces the event monitor's current schedule. The new
     * schedule takes effect from the next scheduler reload, and the old schedule
     * stops firing. The reference job cannot be changed.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<UpdateMonitorResponseDto>> updateMonitor(
            String monitorId, RequestOptions requestOptions) {
        return updateMonitor(monitorId, UpdateMonitorRequestDto.builder().build(), requestOptions);
    }

    /**
     * Update the webhook assignments, record limit, or schedule of an existing
     * event monitor. Omitted fields are left unchanged.
     * <p>Passing <code>schedule</code> replaces the event monitor's current schedule. The new
     * schedule takes effect from the next scheduler reload, and the old schedule
     * stops firing. The reference job cannot be changed.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<UpdateMonitorResponseDto>> updateMonitor(
            String monitorId, UpdateMonitorRequestDto request) {
        return updateMonitor(monitorId, request, null);
    }

    /**
     * Update the webhook assignments, record limit, or schedule of an existing
     * event monitor. Omitted fields are left unchanged.
     * <p>Passing <code>schedule</code> replaces the event monitor's current schedule. The new
     * schedule takes effect from the next scheduler reload, and the old schedule
     * stops firing. The reference job cannot be changed.</p>
     */
    public CompletableFuture<CatchAllApiHttpResponse<UpdateMonitorResponseDto>> updateMonitor(
            String monitorId, UpdateMonitorRequestDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/monitors")
                .addPathSegment(monitorId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CatchAllApiHttpResponse<UpdateMonitorResponseDto>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CatchAllApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateMonitorResponseDto.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ValidationErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CatchAllApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CatchAllApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CatchAllApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
