/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.eventmonitors;

import com.newscatcher.catchall.core.ClientOptions;
import com.newscatcher.catchall.core.RequestOptions;
import com.newscatcher.catchall.resources.eventmonitors.requests.CreateMonitorRequestDto;
import com.newscatcher.catchall.resources.eventmonitors.requests.DeleteMonitorRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.DisableMonitorRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.EnableMonitorRequestDto;
import com.newscatcher.catchall.resources.eventmonitors.requests.GetMonitorStatusHistoryRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.ListMonitorJobsRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.ListMonitorsRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.PullMonitorResultsCsvRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.PullMonitorResultsRequest;
import com.newscatcher.catchall.resources.eventmonitors.requests.UpdateMonitorRequestDto;
import com.newscatcher.catchall.resources.eventmonitors.types.DisableMonitorResponse;
import com.newscatcher.catchall.resources.eventmonitors.types.EnableMonitorResponse;
import com.newscatcher.catchall.resources.eventmonitors.types.ListMonitorJobsResponse;
import com.newscatcher.catchall.types.CreateMonitorResponseDto;
import com.newscatcher.catchall.types.DeleteMonitorResponseDto;
import com.newscatcher.catchall.types.ListMonitorsResponseDto;
import com.newscatcher.catchall.types.MonitorStatusHistoryResponseDto;
import com.newscatcher.catchall.types.PullMonitorResponseDto;
import com.newscatcher.catchall.types.UpdateMonitorResponseDto;

public class EventMonitorsClient {
    protected final ClientOptions clientOptions;

    private final RawEventMonitorsClient rawClient;

    public EventMonitorsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawEventMonitorsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawEventMonitorsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns all event monitors created by the authenticated user.
     */
    public ListMonitorsResponseDto listMonitors() {
        return this.rawClient.listMonitors().body();
    }

    /**
     * Returns all event monitors created by the authenticated user.
     */
    public ListMonitorsResponseDto listMonitors(RequestOptions requestOptions) {
        return this.rawClient.listMonitors(requestOptions).body();
    }

    /**
     * Returns all event monitors created by the authenticated user.
     */
    public ListMonitorsResponseDto listMonitors(ListMonitorsRequest request) {
        return this.rawClient.listMonitors(request).body();
    }

    /**
     * Returns all event monitors created by the authenticated user.
     */
    public ListMonitorsResponseDto listMonitors(ListMonitorsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listMonitors(request, requestOptions).body();
    }

    /**
     * Create a scheduled event monitor based on a reference job.
     */
    public CreateMonitorResponseDto createMonitor(CreateMonitorRequestDto request) {
        return this.rawClient.createMonitor(request).body();
    }

    /**
     * Create a scheduled event monitor based on a reference job.
     */
    public CreateMonitorResponseDto createMonitor(CreateMonitorRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.createMonitor(request, requestOptions).body();
    }

    /**
     * Retrieve aggregated results from all jobs executed by an event monitor.
     */
    public PullMonitorResponseDto pullMonitorResults(String monitorId) {
        return this.rawClient.pullMonitorResults(monitorId).body();
    }

    /**
     * Retrieve aggregated results from all jobs executed by an event monitor.
     */
    public PullMonitorResponseDto pullMonitorResults(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.pullMonitorResults(monitorId, requestOptions).body();
    }

    /**
     * Retrieve aggregated results from all jobs executed by an event monitor.
     */
    public PullMonitorResponseDto pullMonitorResults(String monitorId, PullMonitorResultsRequest request) {
        return this.rawClient.pullMonitorResults(monitorId, request).body();
    }

    /**
     * Retrieve aggregated results from all jobs executed by an event monitor.
     */
    public PullMonitorResponseDto pullMonitorResults(
            String monitorId, PullMonitorResultsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .pullMonitorResults(monitorId, request, requestOptions)
                .body();
    }

    /**
     * Returns the most recent run's records as a CSV download. One row per record, with enrichment fields as columns and citations as a JSON column.
     * <p>If the event monitor's reference job used connected entity datasets, connected entities are split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns. When no entity dataset was used, those two columns are omitted from the export entirely.</p>
     */
    public String pullMonitorResultsCsv(String monitorId) {
        return this.rawClient.pullMonitorResultsCsv(monitorId).body();
    }

    /**
     * Returns the most recent run's records as a CSV download. One row per record, with enrichment fields as columns and citations as a JSON column.
     * <p>If the event monitor's reference job used connected entity datasets, connected entities are split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns. When no entity dataset was used, those two columns are omitted from the export entirely.</p>
     */
    public String pullMonitorResultsCsv(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.pullMonitorResultsCsv(monitorId, requestOptions).body();
    }

    /**
     * Returns the most recent run's records as a CSV download. One row per record, with enrichment fields as columns and citations as a JSON column.
     * <p>If the event monitor's reference job used connected entity datasets, connected entities are split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns. When no entity dataset was used, those two columns are omitted from the export entirely.</p>
     */
    public String pullMonitorResultsCsv(String monitorId, PullMonitorResultsCsvRequest request) {
        return this.rawClient.pullMonitorResultsCsv(monitorId, request).body();
    }

    /**
     * Returns the most recent run's records as a CSV download. One row per record, with enrichment fields as columns and citations as a JSON column.
     * <p>If the event monitor's reference job used connected entity datasets, connected entities are split into <code>event_associated_entities</code> and <code>mention_entities</code> JSON columns. When no entity dataset was used, those two columns are omitted from the export entirely.</p>
     */
    public String pullMonitorResultsCsv(
            String monitorId, PullMonitorResultsCsvRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .pullMonitorResultsCsv(monitorId, request, requestOptions)
                .body();
    }

    /**
     * Return all jobs executed by an event monitor.
     */
    public ListMonitorJobsResponse listMonitorJobs(String monitorId) {
        return this.rawClient.listMonitorJobs(monitorId).body();
    }

    /**
     * Return all jobs executed by an event monitor.
     */
    public ListMonitorJobsResponse listMonitorJobs(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.listMonitorJobs(monitorId, requestOptions).body();
    }

    /**
     * Return all jobs executed by an event monitor.
     */
    public ListMonitorJobsResponse listMonitorJobs(String monitorId, ListMonitorJobsRequest request) {
        return this.rawClient.listMonitorJobs(monitorId, request).body();
    }

    /**
     * Return all jobs executed by an event monitor.
     */
    public ListMonitorJobsResponse listMonitorJobs(
            String monitorId, ListMonitorJobsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .listMonitorJobs(monitorId, request, requestOptions)
                .body();
    }

    /**
     * Returns the full execution history of an event monitor as a list of status entries, ordered from newest to oldest.
     */
    public MonitorStatusHistoryResponseDto getMonitorStatusHistory(String monitorId) {
        return this.rawClient.getMonitorStatusHistory(monitorId).body();
    }

    /**
     * Returns the full execution history of an event monitor as a list of status entries, ordered from newest to oldest.
     */
    public MonitorStatusHistoryResponseDto getMonitorStatusHistory(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.getMonitorStatusHistory(monitorId, requestOptions).body();
    }

    /**
     * Returns the full execution history of an event monitor as a list of status entries, ordered from newest to oldest.
     */
    public MonitorStatusHistoryResponseDto getMonitorStatusHistory(
            String monitorId, GetMonitorStatusHistoryRequest request) {
        return this.rawClient.getMonitorStatusHistory(monitorId, request).body();
    }

    /**
     * Returns the full execution history of an event monitor as a list of status entries, ordered from newest to oldest.
     */
    public MonitorStatusHistoryResponseDto getMonitorStatusHistory(
            String monitorId, GetMonitorStatusHistoryRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getMonitorStatusHistory(monitorId, request, requestOptions)
                .body();
    }

    /**
     * Resume scheduled job execution for an event monitor.
     */
    public EnableMonitorResponse enableMonitor(String monitorId) {
        return this.rawClient.enableMonitor(monitorId).body();
    }

    /**
     * Resume scheduled job execution for an event monitor.
     */
    public EnableMonitorResponse enableMonitor(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.enableMonitor(monitorId, requestOptions).body();
    }

    /**
     * Resume scheduled job execution for an event monitor.
     */
    public EnableMonitorResponse enableMonitor(String monitorId, EnableMonitorRequestDto request) {
        return this.rawClient.enableMonitor(monitorId, request).body();
    }

    /**
     * Resume scheduled job execution for an event monitor.
     */
    public EnableMonitorResponse enableMonitor(
            String monitorId, EnableMonitorRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.enableMonitor(monitorId, request, requestOptions).body();
    }

    /**
     * Stop scheduled job execution for an event monitor.
     */
    public DisableMonitorResponse disableMonitor(String monitorId) {
        return this.rawClient.disableMonitor(monitorId).body();
    }

    /**
     * Stop scheduled job execution for an event monitor.
     */
    public DisableMonitorResponse disableMonitor(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.disableMonitor(monitorId, requestOptions).body();
    }

    /**
     * Stop scheduled job execution for an event monitor.
     */
    public DisableMonitorResponse disableMonitor(String monitorId, DisableMonitorRequest request) {
        return this.rawClient.disableMonitor(monitorId, request).body();
    }

    /**
     * Stop scheduled job execution for an event monitor.
     */
    public DisableMonitorResponse disableMonitor(
            String monitorId, DisableMonitorRequest request, RequestOptions requestOptions) {
        return this.rawClient.disableMonitor(monitorId, request, requestOptions).body();
    }

    /**
     * Soft-deletes an event monitor. The event monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the event monitor owner can delete an event monitor. Returns <code>404</code> if the
     * event monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted event monitor returns <code>200</code>.</p>
     */
    public DeleteMonitorResponseDto deleteMonitor(String monitorId) {
        return this.rawClient.deleteMonitor(monitorId).body();
    }

    /**
     * Soft-deletes an event monitor. The event monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the event monitor owner can delete an event monitor. Returns <code>404</code> if the
     * event monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted event monitor returns <code>200</code>.</p>
     */
    public DeleteMonitorResponseDto deleteMonitor(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.deleteMonitor(monitorId, requestOptions).body();
    }

    /**
     * Soft-deletes an event monitor. The event monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the event monitor owner can delete an event monitor. Returns <code>404</code> if the
     * event monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted event monitor returns <code>200</code>.</p>
     */
    public DeleteMonitorResponseDto deleteMonitor(String monitorId, DeleteMonitorRequest request) {
        return this.rawClient.deleteMonitor(monitorId, request).body();
    }

    /**
     * Soft-deletes an event monitor. The event monitor is flagged as deleted, stops
     * executing scheduled jobs immediately, and no longer appears in list
     * results.
     * <p>Only the event monitor owner can delete an event monitor. Returns <code>404</code> if the
     * event monitor is not found or does not belong to the authenticated user.</p>
     * <p>Deleting an already-deleted event monitor returns <code>200</code>.</p>
     */
    public DeleteMonitorResponseDto deleteMonitor(
            String monitorId, DeleteMonitorRequest request, RequestOptions requestOptions) {
        return this.rawClient.deleteMonitor(monitorId, request, requestOptions).body();
    }

    /**
     * Update the webhook assignments, record limit, or schedule of an existing
     * event monitor. Omitted fields are left unchanged.
     * <p>Passing <code>schedule</code> replaces the event monitor's current schedule. The new
     * schedule takes effect from the next scheduler reload, and the old schedule
     * stops firing. The reference job cannot be changed.</p>
     */
    public UpdateMonitorResponseDto updateMonitor(String monitorId) {
        return this.rawClient.updateMonitor(monitorId).body();
    }

    /**
     * Update the webhook assignments, record limit, or schedule of an existing
     * event monitor. Omitted fields are left unchanged.
     * <p>Passing <code>schedule</code> replaces the event monitor's current schedule. The new
     * schedule takes effect from the next scheduler reload, and the old schedule
     * stops firing. The reference job cannot be changed.</p>
     */
    public UpdateMonitorResponseDto updateMonitor(String monitorId, RequestOptions requestOptions) {
        return this.rawClient.updateMonitor(monitorId, requestOptions).body();
    }

    /**
     * Update the webhook assignments, record limit, or schedule of an existing
     * event monitor. Omitted fields are left unchanged.
     * <p>Passing <code>schedule</code> replaces the event monitor's current schedule. The new
     * schedule takes effect from the next scheduler reload, and the old schedule
     * stops firing. The reference job cannot be changed.</p>
     */
    public UpdateMonitorResponseDto updateMonitor(String monitorId, UpdateMonitorRequestDto request) {
        return this.rawClient.updateMonitor(monitorId, request).body();
    }

    /**
     * Update the webhook assignments, record limit, or schedule of an existing
     * event monitor. Omitted fields are left unchanged.
     * <p>Passing <code>schedule</code> replaces the event monitor's current schedule. The new
     * schedule takes effect from the next scheduler reload, and the old schedule
     * stops firing. The reference job cannot be changed.</p>
     */
    public UpdateMonitorResponseDto updateMonitor(
            String monitorId, UpdateMonitorRequestDto request, RequestOptions requestOptions) {
        return this.rawClient.updateMonitor(monitorId, request, requestOptions).body();
    }
}
