/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.entities;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.newscatcher.catchall.core.CatchAllApiApiException;
import com.newscatcher.catchall.core.CatchAllApiException;
import com.newscatcher.catchall.core.CatchAllApiHttpResponse;
import com.newscatcher.catchall.core.ClientOptions;
import com.newscatcher.catchall.core.MediaTypes;
import com.newscatcher.catchall.core.ObjectMappers;
import com.newscatcher.catchall.core.QueryStringMapper;
import com.newscatcher.catchall.core.RequestOptions;
import com.newscatcher.catchall.errors.BadRequestError;
import com.newscatcher.catchall.errors.ForbiddenError;
import com.newscatcher.catchall.errors.NotFoundError;
import com.newscatcher.catchall.resources.entities.requests.CreateEntitiesBatchRequest;
import com.newscatcher.catchall.resources.entities.requests.DeleteEntityRequest;
import com.newscatcher.catchall.resources.entities.requests.GetEntityRequest;
import com.newscatcher.catchall.resources.entities.requests.ListEntitiesRequest;
import com.newscatcher.catchall.resources.entities.requests.UpdateEntityRequest;
import com.newscatcher.catchall.types.CreateEntitiesBatchResponse;
import com.newscatcher.catchall.types.CreateEntityRequest;
import com.newscatcher.catchall.types.CreateEntityResponse;
import com.newscatcher.catchall.types.EntityListResponse;
import com.newscatcher.catchall.types.EntityResponse;
import com.newscatcher.catchall.types.Error;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawEntitiesClient {
    protected final ClientOptions clientOptions;

    public RawEntitiesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns a paginated list of entities belonging to the authenticated organization. Supports filtering by status and entity type, and sorting by name, status, or creation date.
     */
    public CatchAllApiHttpResponse<EntityListResponse> listEntities() {
        return listEntities(ListEntitiesRequest.builder().build());
    }

    /**
     * Returns a paginated list of entities belonging to the authenticated organization. Supports filtering by status and entity type, and sorting by name, status, or creation date.
     */
    public CatchAllApiHttpResponse<EntityListResponse> listEntities(RequestOptions requestOptions) {
        return listEntities(ListEntitiesRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a paginated list of entities belonging to the authenticated organization. Supports filtering by status and entity type, and sorting by name, status, or creation date.
     */
    public CatchAllApiHttpResponse<EntityListResponse> listEntities(ListEntitiesRequest request) {
        return listEntities(request, null);
    }

    /**
     * Returns a paginated list of entities belonging to the authenticated organization. Supports filtering by status and entity type, and sorting by name, status, or creation date.
     */
    public CatchAllApiHttpResponse<EntityListResponse> listEntities(
            ListEntitiesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/entities");
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPageSize().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page_size", request.getPageSize().get(), false);
        }
        if (request.getSearch().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "search", request.getSearch().get(), false);
        }
        if (request.getStatus().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "status", request.getStatus().get(), false);
        }
        if (request.getEntityType().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "entity_type", request.getEntityType().get(), false);
        }
        if (request.getSortBy().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort_by", request.getSortBy().get(), false);
        }
        if (request.getSortOrder().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "sort_order", request.getSortOrder().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, EntityListResponse.class), response);
            }
            try {
                if (response.code() == 403) {
                    throw new ForbiddenError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Creates a new company entity and begins background enrichment.
     * <p>The entity status starts as <code>pending</code> and transitions to <code>ready</code> once
     * enrichment completes. Provide as much identifying information as
     * possible — <code>domain</code> is the highest-signal field because it is
     * unambiguous.</p>
     */
    public CatchAllApiHttpResponse<CreateEntityResponse> createEntity(CreateEntityRequest request) {
        return createEntity(request, null);
    }

    /**
     * Creates a new company entity and begins background enrichment.
     * <p>The entity status starts as <code>pending</code> and transitions to <code>ready</code> once
     * enrichment completes. Provide as much identifying information as
     * possible — <code>domain</code> is the highest-signal field because it is
     * unambiguous.</p>
     */
    public CatchAllApiHttpResponse<CreateEntityResponse> createEntity(
            CreateEntityRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/entities");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateEntityResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Creates multiple entities in a single request. Each entity is processed independently — a failure in one does not affect others.
     * <p>Returns an array of <code>{id, status}</code> objects in the same order as the input array.</p>
     */
    public CatchAllApiHttpResponse<CreateEntitiesBatchResponse> createEntitiesBatch(
            CreateEntitiesBatchRequest request) {
        return createEntitiesBatch(request, null);
    }

    /**
     * Creates multiple entities in a single request. Each entity is processed independently — a failure in one does not affect others.
     * <p>Returns an array of <code>{id, status}</code> objects in the same order as the input array.</p>
     */
    public CatchAllApiHttpResponse<CreateEntitiesBatchResponse> createEntitiesBatch(
            CreateEntitiesBatchRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/entities/batch");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateEntitiesBatchResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns a single entity by ID with all attributes and current status.
     */
    public CatchAllApiHttpResponse<EntityResponse> getEntity(String entityId) {
        return getEntity(entityId, GetEntityRequest.builder().build());
    }

    /**
     * Returns a single entity by ID with all attributes and current status.
     */
    public CatchAllApiHttpResponse<EntityResponse> getEntity(String entityId, RequestOptions requestOptions) {
        return getEntity(entityId, GetEntityRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a single entity by ID with all attributes and current status.
     */
    public CatchAllApiHttpResponse<EntityResponse> getEntity(String entityId, GetEntityRequest request) {
        return getEntity(entityId, request, null);
    }

    /**
     * Returns a single entity by ID with all attributes and current status.
     */
    public CatchAllApiHttpResponse<EntityResponse> getEntity(
            String entityId, GetEntityRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/entities")
                .addPathSegment(entityId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, EntityResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Permanently deletes an entity. The entity is removed from all
     * datasets and the search index. This operation cannot be undone.
     */
    public CatchAllApiHttpResponse<Void> deleteEntity(String entityId) {
        return deleteEntity(entityId, DeleteEntityRequest.builder().build());
    }

    /**
     * Permanently deletes an entity. The entity is removed from all
     * datasets and the search index. This operation cannot be undone.
     */
    public CatchAllApiHttpResponse<Void> deleteEntity(String entityId, RequestOptions requestOptions) {
        return deleteEntity(entityId, DeleteEntityRequest.builder().build(), requestOptions);
    }

    /**
     * Permanently deletes an entity. The entity is removed from all
     * datasets and the search index. This operation cannot be undone.
     */
    public CatchAllApiHttpResponse<Void> deleteEntity(String entityId, DeleteEntityRequest request) {
        return deleteEntity(entityId, request, null);
    }

    /**
     * Permanently deletes an entity. The entity is removed from all
     * datasets and the search index. This operation cannot be undone.
     */
    public CatchAllApiHttpResponse<Void> deleteEntity(
            String entityId, DeleteEntityRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/entities")
                .addPathSegment(entityId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Updates one or more fields of an existing entity.
     */
    public CatchAllApiHttpResponse<EntityResponse> updateEntity(String entityId) {
        return updateEntity(entityId, UpdateEntityRequest.builder().build());
    }

    /**
     * Updates one or more fields of an existing entity.
     */
    public CatchAllApiHttpResponse<EntityResponse> updateEntity(String entityId, RequestOptions requestOptions) {
        return updateEntity(entityId, UpdateEntityRequest.builder().build(), requestOptions);
    }

    /**
     * Updates one or more fields of an existing entity.
     */
    public CatchAllApiHttpResponse<EntityResponse> updateEntity(String entityId, UpdateEntityRequest request) {
        return updateEntity(entityId, request, null);
    }

    /**
     * Updates one or more fields of an existing entity.
     */
    public CatchAllApiHttpResponse<EntityResponse> updateEntity(
            String entityId, UpdateEntityRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("catchAll/entities")
                .addPathSegment(entityId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new CatchAllApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new CatchAllApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, EntityResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new CatchAllApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new CatchAllApiException("Network error executing HTTP request", e);
        }
    }
}
