/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.monitors.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EnableMonitorRequestDto.Builder.class)
public final class EnableMonitorRequestDto {
    private final Optional<Boolean> backfill;

    private final Map<String, Object> additionalProperties;

    private EnableMonitorRequestDto(Optional<Boolean> backfill, Map<String, Object> additionalProperties) {
        this.backfill = backfill;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return If true, fills the data gap between the last job's <code>end_date</code> and the first scheduled run after enabling. The last job's <code>end_date</code> must be within the last 7 days.
     * <p>If false, no gap filling occurs and the first run uses the current cron window only — the last job's age does not matter.</p>
     */
    @JsonProperty("backfill")
    public Optional<Boolean> getBackfill() {
        return backfill;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EnableMonitorRequestDto && equalTo((EnableMonitorRequestDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EnableMonitorRequestDto other) {
        return backfill.equals(other.backfill);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.backfill);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> backfill = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(EnableMonitorRequestDto other) {
            backfill(other.getBackfill());
            return this;
        }

        /**
         * <p>If true, fills the data gap between the last job's <code>end_date</code> and the first scheduled run after enabling. The last job's <code>end_date</code> must be within the last 7 days.</p>
         * <p>If false, no gap filling occurs and the first run uses the current cron window only — the last job's age does not matter.</p>
         */
        @JsonSetter(value = "backfill", nulls = Nulls.SKIP)
        public Builder backfill(Optional<Boolean> backfill) {
            this.backfill = backfill;
            return this;
        }

        public Builder backfill(Boolean backfill) {
            this.backfill = Optional.ofNullable(backfill);
            return this;
        }

        public EnableMonitorRequestDto build() {
            return new EnableMonitorRequestDto(backfill, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
