/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.monitors.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateMonitorRequestDto.Builder.class)
public final class UpdateMonitorRequestDto {
    private final Optional<List<String>> webhookIds;

    private final Optional<Integer> limit;

    private final Map<String, Object> additionalProperties;

    private UpdateMonitorRequestDto(
            Optional<List<String>> webhookIds, Optional<Integer> limit, Map<String, Object> additionalProperties) {
        this.webhookIds = webhookIds;
        this.limit = limit;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Updated list of centralized webhook IDs for this monitor.
     * <p>Replaces all existing webhook assignments. Pass an empty array <code>[]</code> to clear all assignments. Omit to leave existing assignments unchanged.</p>
     */
    @JsonProperty("webhook_ids")
    public Optional<List<String>> getWebhookIds() {
        return webhookIds;
    }

    /**
     * @return Updated maximum number of records per monitor run.
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateMonitorRequestDto && equalTo((UpdateMonitorRequestDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateMonitorRequestDto other) {
        return webhookIds.equals(other.webhookIds) && limit.equals(other.limit);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.webhookIds, this.limit);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<String>> webhookIds = Optional.empty();

        private Optional<Integer> limit = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateMonitorRequestDto other) {
            webhookIds(other.getWebhookIds());
            limit(other.getLimit());
            return this;
        }

        /**
         * <p>Updated list of centralized webhook IDs for this monitor.</p>
         * <p>Replaces all existing webhook assignments. Pass an empty array <code>[]</code> to clear all assignments. Omit to leave existing assignments unchanged.</p>
         */
        @JsonSetter(value = "webhook_ids", nulls = Nulls.SKIP)
        public Builder webhookIds(Optional<List<String>> webhookIds) {
            this.webhookIds = webhookIds;
            return this;
        }

        public Builder webhookIds(List<String> webhookIds) {
            this.webhookIds = Optional.ofNullable(webhookIds);
            return this;
        }

        /**
         * <p>Updated maximum number of records per monitor run.</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        public UpdateMonitorRequestDto build() {
            return new UpdateMonitorRequestDto(webhookIds, limit, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
