/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.jobs.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ContinueRequestDto.Builder.class)
public final class ContinueRequestDto {
    private final String jobId;

    private final int newLimit;

    private final Map<String, Object> additionalProperties;

    private ContinueRequestDto(String jobId, int newLimit, Map<String, Object> additionalProperties) {
        this.jobId = jobId;
        this.newLimit = newLimit;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Job identifier of the completed job to continue.
     */
    @JsonProperty("job_id")
    public String getJobId() {
        return jobId;
    }

    /**
     * @return New record limit for continued processing. Must be greater than the previous limit.
     */
    @JsonProperty("new_limit")
    public int getNewLimit() {
        return newLimit;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ContinueRequestDto && equalTo((ContinueRequestDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ContinueRequestDto other) {
        return jobId.equals(other.jobId) && newLimit == other.newLimit;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.jobId, this.newLimit);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static JobIdStage builder() {
        return new Builder();
    }

    public interface JobIdStage {
        /**
         * <p>Job identifier of the completed job to continue.</p>
         */
        NewLimitStage jobId(@NotNull String jobId);

        Builder from(ContinueRequestDto other);
    }

    public interface NewLimitStage {
        /**
         * <p>New record limit for continued processing. Must be greater than the previous limit.</p>
         */
        _FinalStage newLimit(int newLimit);
    }

    public interface _FinalStage {
        ContinueRequestDto build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements JobIdStage, NewLimitStage, _FinalStage {
        private String jobId;

        private int newLimit;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ContinueRequestDto other) {
            jobId(other.getJobId());
            newLimit(other.getNewLimit());
            return this;
        }

        /**
         * <p>Job identifier of the completed job to continue.</p>
         * <p>Job identifier of the completed job to continue.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("job_id")
        public NewLimitStage jobId(@NotNull String jobId) {
            this.jobId = Objects.requireNonNull(jobId, "jobId must not be null");
            return this;
        }

        /**
         * <p>New record limit for continued processing. Must be greater than the previous limit.</p>
         * <p>New record limit for continued processing. Must be greater than the previous limit.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("new_limit")
        public _FinalStage newLimit(int newLimit) {
            this.newLimit = newLimit;
            return this;
        }

        @java.lang.Override
        public ContinueRequestDto build() {
            return new ContinueRequestDto(jobId, newLimit, additionalProperties);
        }
    }
}
