/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.jobs.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SubmitRequestDto.Builder.class)
public final class SubmitRequestDto {
    private final String query;

    private final Optional<String> schema;

    private final Optional<String> context;

    private final Optional<Integer> limit;

    private final Map<String, Object> additionalProperties;

    private SubmitRequestDto(
            String query,
            Optional<String> schema,
            Optional<String> context,
            Optional<Integer> limit,
            Map<String, Object> additionalProperties) {
        this.query = query;
        this.schema = schema;
        this.context = context;
        this.limit = limit;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("query")
    public String getQuery() {
        return query;
    }

    @JsonProperty("schema")
    public Optional<String> getSchema() {
        return schema;
    }

    @JsonProperty("context")
    public Optional<String> getContext() {
        return context;
    }

    /**
     * @return Maximum number of records to return. If not specified, defaults to your plan limit.
     * <p>Use /catchAll/continue to extend the limit after job completion without reprocessing.</p>
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SubmitRequestDto && equalTo((SubmitRequestDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SubmitRequestDto other) {
        return query.equals(other.query)
                && schema.equals(other.schema)
                && context.equals(other.context)
                && limit.equals(other.limit);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.query, this.schema, this.context, this.limit);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static QueryStage builder() {
        return new Builder();
    }

    public interface QueryStage {
        _FinalStage query(@NotNull String query);

        Builder from(SubmitRequestDto other);
    }

    public interface _FinalStage {
        SubmitRequestDto build();

        _FinalStage schema(Optional<String> schema);

        _FinalStage schema(String schema);

        _FinalStage context(Optional<String> context);

        _FinalStage context(String context);

        /**
         * <p>Maximum number of records to return. If not specified, defaults to your plan limit.</p>
         * <p>Use /catchAll/continue to extend the limit after job completion without reprocessing.</p>
         */
        _FinalStage limit(Optional<Integer> limit);

        _FinalStage limit(Integer limit);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements QueryStage, _FinalStage {
        private String query;

        private Optional<Integer> limit = Optional.empty();

        private Optional<String> context = Optional.empty();

        private Optional<String> schema = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SubmitRequestDto other) {
            query(other.getQuery());
            schema(other.getSchema());
            context(other.getContext());
            limit(other.getLimit());
            return this;
        }

        @java.lang.Override
        @JsonSetter("query")
        public _FinalStage query(@NotNull String query) {
            this.query = Objects.requireNonNull(query, "query must not be null");
            return this;
        }

        /**
         * <p>Maximum number of records to return. If not specified, defaults to your plan limit.</p>
         * <p>Use /catchAll/continue to extend the limit after job completion without reprocessing.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Maximum number of records to return. If not specified, defaults to your plan limit.</p>
         * <p>Use /catchAll/continue to extend the limit after job completion without reprocessing.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public _FinalStage limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        @java.lang.Override
        public _FinalStage context(String context) {
            this.context = Optional.ofNullable(context);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "context", nulls = Nulls.SKIP)
        public _FinalStage context(Optional<String> context) {
            this.context = context;
            return this;
        }

        @java.lang.Override
        public _FinalStage schema(String schema) {
            this.schema = Optional.ofNullable(schema);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "schema", nulls = Nulls.SKIP)
        public _FinalStage schema(Optional<String> schema) {
            this.schema = schema;
            return this;
        }

        @java.lang.Override
        public SubmitRequestDto build() {
            return new SubmitRequestDto(query, schema, context, limit, additionalProperties);
        }
    }
}
