/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.webhooks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TestWebhookRequestDto.Builder.class)
public final class TestWebhookRequestDto {
    private final Optional<Map<String, Object>> payload;

    private final Map<String, Object> additionalProperties;

    private TestWebhookRequestDto(Optional<Map<String, Object>> payload, Map<String, Object> additionalProperties) {
        this.payload = payload;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Custom payload to send in the test request. If omitted, a synthetic
     * test payload is sent.
     */
    @JsonProperty("payload")
    public Optional<Map<String, Object>> getPayload() {
        return payload;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TestWebhookRequestDto && equalTo((TestWebhookRequestDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TestWebhookRequestDto other) {
        return payload.equals(other.payload);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.payload);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Map<String, Object>> payload = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TestWebhookRequestDto other) {
            payload(other.getPayload());
            return this;
        }

        /**
         * <p>Custom payload to send in the test request. If omitted, a synthetic
         * test payload is sent.</p>
         */
        @JsonSetter(value = "payload", nulls = Nulls.SKIP)
        public Builder payload(Optional<Map<String, Object>> payload) {
            this.payload = payload;
            return this;
        }

        public Builder payload(Map<String, Object> payload) {
            this.payload = Optional.ofNullable(payload);
            return this;
        }

        public TestWebhookRequestDto build() {
            return new TestWebhookRequestDto(payload, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
