/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.newscatcher.catchall.resources.webhooks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.newscatcher.catchall.core.Nullable;
import com.newscatcher.catchall.core.NullableNonemptyFilter;
import com.newscatcher.catchall.core.ObjectMappers;
import com.newscatcher.catchall.resources.webhooks.types.UpdateWebhookRequestDtoAuth;
import com.newscatcher.catchall.types.DeliveryMode;
import com.newscatcher.catchall.types.HttpMethod;
import com.newscatcher.catchall.types.WebhookType;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateWebhookRequestDto.Builder.class)
public final class UpdateWebhookRequestDto {
    private final Optional<String> name;

    private final Optional<String> url;

    private final Optional<WebhookType> type;

    private final Optional<DeliveryMode> deliveryMode;

    private final Optional<HttpMethod> method;

    private final Optional<Map<String, String>> headers;

    private final Optional<Map<String, String>> params;

    private final Optional<UpdateWebhookRequestDtoAuth> auth;

    private final Optional<Map<String, Object>> formatterConfig;

    private final Optional<Boolean> isActive;

    private final Map<String, Object> additionalProperties;

    private UpdateWebhookRequestDto(
            Optional<String> name,
            Optional<String> url,
            Optional<WebhookType> type,
            Optional<DeliveryMode> deliveryMode,
            Optional<HttpMethod> method,
            Optional<Map<String, String>> headers,
            Optional<Map<String, String>> params,
            Optional<UpdateWebhookRequestDtoAuth> auth,
            Optional<Map<String, Object>> formatterConfig,
            Optional<Boolean> isActive,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.url = url;
        this.type = type;
        this.deliveryMode = deliveryMode;
        this.method = method;
        this.headers = headers;
        this.params = params;
        this.auth = auth;
        this.formatterConfig = formatterConfig;
        this.isActive = isActive;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Updated webhook name.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Updated destination URL. Must use HTTPS. Type-specific URL rules apply.
     */
    @JsonProperty("url")
    public Optional<String> getUrl() {
        return url;
    }

    @JsonProperty("type")
    public Optional<WebhookType> getType() {
        return type;
    }

    @JsonProperty("delivery_mode")
    public Optional<DeliveryMode> getDeliveryMode() {
        return deliveryMode;
    }

    @JsonProperty("method")
    public Optional<HttpMethod> getMethod() {
        return method;
    }

    /**
     * @return Updated HTTP headers. Replaces existing headers entirely.
     */
    @JsonProperty("headers")
    public Optional<Map<String, String>> getHeaders() {
        return headers;
    }

    /**
     * @return Updated query parameters. Replaces existing params entirely.
     */
    @JsonProperty("params")
    public Optional<Map<String, String>> getParams() {
        return params;
    }

    /**
     * @return Updated authentication configuration. Replaces existing auth entirely.
     */
    @JsonProperty("auth")
    public Optional<UpdateWebhookRequestDtoAuth> getAuth() {
        return auth;
    }

    /**
     * @return Updated formatter configuration.
     */
    @JsonIgnore
    public Optional<Map<String, Object>> getFormatterConfig() {
        if (formatterConfig == null) {
            return Optional.empty();
        }
        return formatterConfig;
    }

    /**
     * @return Set to <code>false</code> to disable delivery without deleting the webhook.
     */
    @JsonProperty("is_active")
    public Optional<Boolean> getIsActive() {
        return isActive;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("formatter_config")
    private Optional<Map<String, Object>> _getFormatterConfig() {
        return formatterConfig;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateWebhookRequestDto && equalTo((UpdateWebhookRequestDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateWebhookRequestDto other) {
        return name.equals(other.name)
                && url.equals(other.url)
                && type.equals(other.type)
                && deliveryMode.equals(other.deliveryMode)
                && method.equals(other.method)
                && headers.equals(other.headers)
                && params.equals(other.params)
                && auth.equals(other.auth)
                && formatterConfig.equals(other.formatterConfig)
                && isActive.equals(other.isActive);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.name,
                this.url,
                this.type,
                this.deliveryMode,
                this.method,
                this.headers,
                this.params,
                this.auth,
                this.formatterConfig,
                this.isActive);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<String> url = Optional.empty();

        private Optional<WebhookType> type = Optional.empty();

        private Optional<DeliveryMode> deliveryMode = Optional.empty();

        private Optional<HttpMethod> method = Optional.empty();

        private Optional<Map<String, String>> headers = Optional.empty();

        private Optional<Map<String, String>> params = Optional.empty();

        private Optional<UpdateWebhookRequestDtoAuth> auth = Optional.empty();

        private Optional<Map<String, Object>> formatterConfig = Optional.empty();

        private Optional<Boolean> isActive = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateWebhookRequestDto other) {
            name(other.getName());
            url(other.getUrl());
            type(other.getType());
            deliveryMode(other.getDeliveryMode());
            method(other.getMethod());
            headers(other.getHeaders());
            params(other.getParams());
            auth(other.getAuth());
            formatterConfig(other.getFormatterConfig());
            isActive(other.getIsActive());
            return this;
        }

        /**
         * <p>Updated webhook name.</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Updated destination URL. Must use HTTPS. Type-specific URL rules apply.</p>
         */
        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public Builder url(Optional<String> url) {
            this.url = url;
            return this;
        }

        public Builder url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<WebhookType> type) {
            this.type = type;
            return this;
        }

        public Builder type(WebhookType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        @JsonSetter(value = "delivery_mode", nulls = Nulls.SKIP)
        public Builder deliveryMode(Optional<DeliveryMode> deliveryMode) {
            this.deliveryMode = deliveryMode;
            return this;
        }

        public Builder deliveryMode(DeliveryMode deliveryMode) {
            this.deliveryMode = Optional.ofNullable(deliveryMode);
            return this;
        }

        @JsonSetter(value = "method", nulls = Nulls.SKIP)
        public Builder method(Optional<HttpMethod> method) {
            this.method = method;
            return this;
        }

        public Builder method(HttpMethod method) {
            this.method = Optional.ofNullable(method);
            return this;
        }

        /**
         * <p>Updated HTTP headers. Replaces existing headers entirely.</p>
         */
        @JsonSetter(value = "headers", nulls = Nulls.SKIP)
        public Builder headers(Optional<Map<String, String>> headers) {
            this.headers = headers;
            return this;
        }

        public Builder headers(Map<String, String> headers) {
            this.headers = Optional.ofNullable(headers);
            return this;
        }

        /**
         * <p>Updated query parameters. Replaces existing params entirely.</p>
         */
        @JsonSetter(value = "params", nulls = Nulls.SKIP)
        public Builder params(Optional<Map<String, String>> params) {
            this.params = params;
            return this;
        }

        public Builder params(Map<String, String> params) {
            this.params = Optional.ofNullable(params);
            return this;
        }

        /**
         * <p>Updated authentication configuration. Replaces existing auth entirely.</p>
         */
        @JsonSetter(value = "auth", nulls = Nulls.SKIP)
        public Builder auth(Optional<UpdateWebhookRequestDtoAuth> auth) {
            this.auth = auth;
            return this;
        }

        public Builder auth(UpdateWebhookRequestDtoAuth auth) {
            this.auth = Optional.ofNullable(auth);
            return this;
        }

        /**
         * <p>Updated formatter configuration.</p>
         */
        @JsonSetter(value = "formatter_config", nulls = Nulls.SKIP)
        public Builder formatterConfig(Optional<Map<String, Object>> formatterConfig) {
            this.formatterConfig = formatterConfig;
            return this;
        }

        public Builder formatterConfig(Map<String, Object> formatterConfig) {
            this.formatterConfig = Optional.ofNullable(formatterConfig);
            return this;
        }

        public Builder formatterConfig(Nullable<Map<String, Object>> formatterConfig) {
            if (formatterConfig.isNull()) {
                this.formatterConfig = null;
            } else if (formatterConfig.isEmpty()) {
                this.formatterConfig = Optional.empty();
            } else {
                this.formatterConfig = Optional.of(formatterConfig.get());
            }
            return this;
        }

        /**
         * <p>Set to <code>false</code> to disable delivery without deleting the webhook.</p>
         */
        @JsonSetter(value = "is_active", nulls = Nulls.SKIP)
        public Builder isActive(Optional<Boolean> isActive) {
            this.isActive = isActive;
            return this;
        }

        public Builder isActive(Boolean isActive) {
            this.isActive = Optional.ofNullable(isActive);
            return this;
        }

        public UpdateWebhookRequestDto build() {
            return new UpdateWebhookRequestDto(
                    name,
                    url,
                    type,
                    deliveryMode,
                    method,
                    headers,
                    params,
                    auth,
                    formatterConfig,
                    isActive,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
